import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";
import { resetSessionCreditsOnPaymentDelete } from "@/lib/payments/utils";

export async function DELETE(request: NextRequest) {
  try {
    const { tenantId, supabase, userId, email } = await getTenantContext();
    const body = await request.json();
    const { ids, studentIds, month } = body;

    const { data: payments } = studentIds && month
      ? await supabase
          .from("payments")
          .select("id, amountDue, amountPaid, month, studentId, groupId, students(fullName)")
          .in("studentId", studentIds)
          .eq("month", month)
          .eq("tenantId", tenantId)
      : await supabase
          .from("payments")
          .select("id, amountDue, amountPaid, month, studentId, groupId, students(fullName)")
          .in("id", ids || [])
          .eq("tenantId", tenantId);

    if (!payments || payments.length === 0) {
      return NextResponse.json({ success: true, deleted: 0 });
    }

    const payIds = payments.map((p) => p.id as string);

    await supabase.from("cash_movements").delete().in("referenceId", payIds).eq("autoGenerated", true);

    for (const p of payments) {
      const amountPaid = Number(p.amountPaid || 0);
      const amountDue = Number(p.amountDue || 0);
      if (amountPaid > amountDue) {
        const excess = amountPaid - amountDue;
        const { data: sd } = await supabase.from("students").select("advanceBalance").eq("id", p.studentId).single();
        const currentAdvance = Number((sd as any)?.advanceBalance || 0);
        await supabase.from("students").update({ advanceBalance: Math.max(0, currentAdvance - excess) }).eq("id", p.studentId);
      }
    }

    await supabase.from("payments").delete().in("id", payIds).eq("tenantId", tenantId);

    // After deleting, reset unused session credits for any affected
    // student+group whose paid payments are now gone.
    const seen = new Set<string>();
    for (const p of payments) {
      const key = `${p.studentId}:${p.groupId ?? "null"}`;
      if (seen.has(key)) continue;
      seen.add(key);
      await resetSessionCreditsOnPaymentDelete({ supabase, tenantId, studentId: p.studentId, groupId: p.groupId ?? null });
    }

    const auditLogs = payments.map((p: Record<string, unknown>) => {
      const raw = p.students as unknown;
      const student = Array.isArray(raw) ? (raw as { fullName?: string }[])[0] : (raw as { fullName?: string } | undefined);
      return {
        id: crypto.randomUUID(),
        tenantId,
        userId,
        action: "payment_deleted",
        entityType: "payment",
        entityId: p.id as string,
        metadata: {
          amountDue: p.amountDue,
          amountPaid: p.amountPaid,
          month: p.month,
          studentName: student?.fullName ?? "Unknown",
          deletedBy: email,
        },
      };
    });

    await supabase.from("audit_logs").insert(auditLogs);

    return NextResponse.json({ success: true, deleted: payments.length });
  } catch {
    return NextResponse.json({ error: "Failed to delete payments" }, { status: 500 });
  }
}
