import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function DELETE(request: NextRequest) {
  try {
    const { tenantId, supabase, userId, email } = await getTenantContext();
    const { ids } = await request.json();

    if (!ids || !Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: "No IDs provided" }, { status: 400 });
    }

    const { data: payments } = await supabase
      .from("payments")
      .select("id, amountDue, amountPaid, month, studentId, students(fullName)")
      .in("id", ids)
      .eq("tenantId", tenantId);

    if (!payments || payments.length === 0) {
      return NextResponse.json({ error: "No payments found" }, { status: 404 });
    }

    const paymentIds = payments.map((p) => p.id as string);

    // Reverse linked cash movements before deleting payments
    await supabase.from("cash_movements").delete().in("referenceId", paymentIds).eq("autoGenerated", true);

    // Reverse advanceBalance for overpaid payments
    for (const p of payments) {
      const amountPaid = Number(p.amountPaid || 0);
      const amountDue = Number(p.amountDue || 0);
      if (amountPaid > amountDue) {
        const excess = amountPaid - amountDue;
        const { data: sd } = await supabase.from("students").select("advanceBalance").eq("id", p.studentId).single();
        const currentAdvance = Number((sd as any)?.advanceBalance || 0);
        await supabase.from("students").update({ advanceBalance: Math.max(0, currentAdvance - excess) }).eq("id", p.studentId);
      }
    }

    await supabase.from("payments").delete().in("id", paymentIds).eq("tenantId", tenantId);

    const auditLogs = payments.map((p: Record<string, unknown>) => {
      const raw = p.students as unknown;
      const student = Array.isArray(raw) ? (raw as { fullName?: string }[])[0] : (raw as { fullName?: string } | undefined);
      return {
        id: crypto.randomUUID(),
        tenantId,
        userId,
        action: "payment_deleted",
        entityType: "payment",
        entityId: p.id as string,
        metadata: {
          amountDue: p.amountDue,
          amountPaid: p.amountPaid,
          month: p.month,
          studentName: student?.fullName ?? "Unknown",
          deletedBy: email,
        },
      };
    });

    await supabase.from("audit_logs").insert(auditLogs);

    return NextResponse.json({ success: true, deleted: payments.length });
  } catch {
    return NextResponse.json({ error: "Failed to delete payments" }, { status: 500 });
  }
}
