// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnySupabase = any;

interface TrashablePayment {
  id: string;
  tenantId: string;
  studentId: string;
  groupId: string | null;
  month: string;
  amountDue: number;
  amountPaid: number;
  discountPercent: number;
  status: string;
  paidAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
  students?: unknown;
  _cashMovements?: unknown[];
}

interface TrashableMovement {
  id: string;
  tenantId: string;
  userId: string;
  type: string;
  category: string;
  amount: number;
  description: string | null;
  paymentMethod: string;
  date: string;
  referenceId: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  _payment?: TrashablePayment;
}

export async function moveToTrashPayment(
  supabase: AnySupabase,
  tenantId: string,
  userId: string,
  payment: TrashablePayment,
  cashMovements?: unknown[]
) {
  const originalData = { ...payment };
  if (cashMovements && cashMovements.length > 0) {
    (originalData as any)._cashMovements = cashMovements;
  }
  delete (originalData as any).students;

  await supabase.from("deleted_items").insert({
    id: crypto.randomUUID(),
    tenantId,
    userId,
    sourceType: "payment",
    originalData: JSON.stringify(originalData),
    description: `Paiement - ${(payment.students as any)?.fullName ?? "Élève"} (${payment.month})`,
    deletedAt: new Date().toISOString(),
  });
}

export async function moveToTrashMovement(
  supabase: AnySupabase,
  tenantId: string,
  userId: string,
  movement: TrashableMovement,
  linkedPayment?: TrashablePayment,
  linkedCashMovements?: unknown[]
) {
  const originalData = { ...movement };
  if (linkedPayment) {
    const pData = { ...linkedPayment };
    if (linkedCashMovements && linkedCashMovements.length > 0) {
      (pData as any)._cashMovements = linkedCashMovements;
    }
    (originalData as any)._payment = pData;
  }

  await supabase.from("deleted_items").insert({
    id: crypto.randomUUID(),
    tenantId,
    userId,
    sourceType: "cash_movement",
    originalData: JSON.stringify(originalData),
    description: movement.description || `${movement.type === "income" ? "Recette" : "Dépense"} - ${movement.amount}`,
    deletedAt: new Date().toISOString(),
  });
}
