import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function GET() {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { data: payments } = await supabase
      .from("teacher_payments")
      .select("*, teachers(firstName, lastName)")
      .eq("tenantId", tenantId)
      .order("periodMonth", { ascending: false });
    return NextResponse.json(payments || []);
  } catch {
    return NextResponse.json({ error: "Failed" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const ctx = await getTenantContext();
    const { tenantId, supabase, userId } = ctx;
    const body = await req.json();
    const { teacherId, periodMonth, amount, notes } = body;

    if (!teacherId || !periodMonth || !amount) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const { data: payment, error } = await supabase
      .from("teacher_payments")
      .insert({
        id: crypto.randomUUID(),
        tenantId,
        teacherId,
        periodMonth,
        amount: Number(amount),
        status: "paid",
        paidAt: new Date().toISOString(),
        notes: notes || null,
      })
      .select("*, teachers(firstName, lastName)")
      .single();

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    await supabase.from("cash_movements").insert({
      id: crypto.randomUUID(),
      tenantId,
      userId,
      type: "expense",
      category: "Salaire",
      amount: Number(amount),
      description: `Salaire enseignant`,
      paymentMethod: "cash",
      date: new Date().toISOString().split("T")[0],
      referenceId: payment.id,
      autoGenerated: true,
    }).maybeSingle();

    return NextResponse.json(payment, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Failed to create payment" }, { status: 500 });
  }
}
