-- ============================================
-- Migration: Receipt numbers + Caisse + Advances
-- ============================================

-- 1. RECEIPT NUMBERS
ALTER TABLE payments ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS "receiptSequence" INTEGER;

CREATE SEQUENCE IF NOT EXISTS receipt_seq MINVALUE 1 START 1;

-- 2. CAISSE SYSTEM
CREATE TABLE IF NOT EXISTS cash_movements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "userId" UUID NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  category TEXT NOT NULL DEFAULT 'general',
  amount DECIMAL(10,2) NOT NULL,
  description TEXT,
  "paymentMethod" TEXT DEFAULT 'cash',
  date DATE DEFAULT CURRENT_DATE,
  "referenceId" UUID,
  "autoGenerated" BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cash_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  color TEXT DEFAULT '#6366f1',
  "createdAt" TIMESTAMP DEFAULT NOW()
);

-- 3. ADVANCE PAYMENTS
ALTER TABLE students ADD COLUMN IF NOT EXISTS "advanceBalance" DECIMAL(10,2) DEFAULT 0;

-- 4. SUBJECT PRICING
CREATE TABLE IF NOT EXISTS subject_pricing (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "subjectId" UUID REFERENCES subjects(id) ON DELETE CASCADE,
  level TEXT NOT NULL,
  "monthlyPrice" DECIMAL(10,2) DEFAULT 0,
  "sessionPrice" DECIMAL(10,2) DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW()
);

-- 5. TEACHERS
CREATE TABLE IF NOT EXISTS teachers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  "salaryType" TEXT CHECK ("salaryType" IN ('fixed', 'per_student', 'per_hour', 'per_session', 'percentage')),
  "salaryAmount" DECIMAL(10,2) DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teacher_payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "teacherId" UUID REFERENCES teachers(id) ON DELETE CASCADE,
  "periodMonth" DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  "paidAt" TIMESTAMP,
  notes TEXT,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

-- 6. WORKSPACES
CREATE TABLE IF NOT EXISTS workspaces (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  name TEXT NOT NULL,
  "isActive" BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

ALTER TABLE groups ADD COLUMN IF NOT EXISTS "workspaceId" UUID REFERENCES workspaces(id) ON DELETE SET NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS "workspaceId" UUID REFERENCES workspaces(id) ON DELETE SET NULL;
