-- ============================================
-- Complete Migration: All 8 Features
-- ============================================

-- FEATURE 2: Receipt Numbers
ALTER TABLE payments ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS "receiptSequence" INTEGER;

-- FEATURE 1: Caisse System
CREATE TABLE IF NOT EXISTS cash_movements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "userId" UUID NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  category TEXT NOT NULL DEFAULT 'general',
  amount DECIMAL(10,2) NOT NULL,
  description TEXT,
  "paymentMethod" TEXT DEFAULT 'cash',
  date DATE DEFAULT CURRENT_DATE,
  "referenceId" UUID,
  "autoGenerated" BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cash_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  color TEXT DEFAULT '#6366f1',
  "createdAt" TIMESTAMP DEFAULT NOW()
);

-- FEATURE 3: Advance Payments
ALTER TABLE students ADD COLUMN IF NOT EXISTS "advanceBalance" DECIMAL(10,2) DEFAULT 0;

-- FEATURE 5: Subject Pricing
CREATE TABLE IF NOT EXISTS subject_pricing (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "subjectId" UUID REFERENCES subjects(id) ON DELETE CASCADE,
  level TEXT NOT NULL,
  "monthlyPrice" DECIMAL(10,2) DEFAULT 0,
  "sessionPrice" DECIMAL(10,2) DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW()
);

-- FEATURE 7: Teachers & Salaries
CREATE TABLE IF NOT EXISTS teachers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  "salaryType" TEXT CHECK ("salaryType" IN ('fixed', 'per_student', 'per_hour', 'per_session', 'percentage')),
  "salaryAmount" DECIMAL(10,2) DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teacher_payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "teacherId" UUID REFERENCES teachers(id) ON DELETE CASCADE,
  "periodMonth" DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  "paidAt" TIMESTAMP,
  notes TEXT,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "teacherId" UUID REFERENCES teachers(id) ON DELETE SET NULL;

-- FEATURE 8: Workspaces
CREATE TABLE IF NOT EXISTS workspaces (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  name TEXT NOT NULL,
  "isActive" BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "workspaceId" UUID REFERENCES workspaces(id) ON DELETE SET NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS "workspaceId" UUID REFERENCES workspaces(id) ON DELETE SET NULL;

-- ============================================
-- Levels Table
-- ============================================
CREATE TABLE IF NOT EXISTS levels (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "tenantId" UUID NOT NULL,
  "nameAr" TEXT NOT NULL,
  "nameFr" TEXT NOT NULL,
  "nameEn" TEXT NOT NULL,
  cycle TEXT NOT NULL DEFAULT 'primary',
  "sortOrder" INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW(),
  UNIQUE("tenantId", "nameAr")
);

ALTER TABLE levels ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tenant_isolation_select" ON levels;
CREATE POLICY "tenant_isolation_select" ON levels
  FOR SELECT
  USING ("tenantId" = current_setting('app.tenant_id', true)::UUID);

DROP POLICY IF EXISTS "tenant_isolation_insert" ON levels;
CREATE POLICY "tenant_isolation_insert" ON levels
  FOR INSERT
  WITH CHECK ("tenantId" = current_setting('app.tenant_id', true)::UUID);

DROP POLICY IF EXISTS "tenant_isolation_update" ON levels;
CREATE POLICY "tenant_isolation_update" ON levels
  FOR UPDATE
  USING ("tenantId" = current_setting('app.tenant_id', true)::UUID);

DROP POLICY IF EXISTS "tenant_isolation_delete" ON levels;
CREATE POLICY "tenant_isolation_delete" ON levels
  FOR DELETE
  USING ("tenantId" = current_setting('app.tenant_id', true)::UUID);

CREATE INDEX IF NOT EXISTS idx_levels_tenantId ON levels("tenantId");
CREATE INDEX IF NOT EXISTS idx_levels_status ON levels("tenantId", "status");

-- ============================================
-- Performance Indexes
-- ============================================
CREATE INDEX IF NOT EXISTS idx_payments_tenantId ON payments("tenantId");
CREATE INDEX IF NOT EXISTS idx_payments_studentId ON payments("studentId");
CREATE INDEX IF NOT EXISTS idx_payments_year_month ON payments("year", "month");
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments("status");
CREATE INDEX IF NOT EXISTS idx_payments_receiptSequence ON payments("tenantId", "receiptSequence");

CREATE INDEX IF NOT EXISTS idx_cash_movements_tenantId ON cash_movements("tenantId");
CREATE INDEX IF NOT EXISTS idx_cash_movements_date ON cash_movements("tenantId", "date");
CREATE INDEX IF NOT EXISTS idx_cash_movements_type ON cash_movements("tenantId", "type");

CREATE INDEX IF NOT EXISTS idx_teacher_payments_tenantId ON teacher_payments("tenantId");
CREATE INDEX IF NOT EXISTS idx_teacher_payments_teacherId ON teacher_payments("tenantId", "teacherId");
CREATE INDEX IF NOT EXISTS idx_teacher_payments_period ON teacher_payments("tenantId", "periodMonth");

CREATE INDEX IF NOT EXISTS idx_subject_pricing_tenantId ON subject_pricing("tenantId");
CREATE INDEX IF NOT EXISTS idx_subject_pricing_subject ON subject_pricing("tenantId", "subjectId");

CREATE INDEX IF NOT EXISTS idx_students_tenantId ON students("tenantId");
CREATE INDEX IF NOT EXISTS idx_students_workspace ON students("tenantId", "workspaceId");
CREATE INDEX IF NOT EXISTS idx_students_status ON students("tenantId", "status");

CREATE INDEX IF NOT EXISTS idx_groups_tenantId ON groups("tenantId");
CREATE INDEX IF NOT EXISTS idx_groups_workspace ON groups("tenantId", "workspaceId");
CREATE INDEX IF NOT EXISTS idx_groups_status ON groups("tenantId", "status");

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS "type" TEXT DEFAULT 'regular';

CREATE INDEX IF NOT EXISTS idx_sessions_tenantId ON sessions("tenantId");
CREATE INDEX IF NOT EXISTS idx_sessions_date ON sessions("tenantId", "sessionDate");

CREATE INDEX IF NOT EXISTS idx_attendance_tenantId ON attendance("tenantId");
CREATE INDEX IF NOT EXISTS idx_attendance_session ON attendance("sessionId");

CREATE INDEX IF NOT EXISTS idx_teachers_tenantId ON teachers("tenantId");

CREATE INDEX IF NOT EXISTS idx_workspaces_tenantId ON workspaces("tenantId");
