import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { id } = await params;

    const { error } = await supabase
      .from("deleted_items")
      .delete()
      .eq("id", id)
      .eq("tenantId", tenantId);

    if (error) throw error;
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Failed to delete item" }, { status: 500 });
  }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase, userId } = await getTenantContext();
    const { id } = await params;

    const { data: item, error: fetchError } = await supabase
      .from("deleted_items")
      .select("*")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (fetchError || !item) {
      return NextResponse.json({ error: "Item not found" }, { status: 404 });
    }

    const originalData = JSON.parse(item.originalData as string);

    if (item.sourceType === "payment") {
      const { data: existingPayment } = await supabase
        .from("payments")
        .select("id")
        .eq("id", originalData.id)
        .single();

      if (existingPayment) {
        await supabase.from("deleted_items").delete().eq("id", id);
        return NextResponse.json({ success: true, warning: "Payment already exists" });
      }

      const paymentRow: Record<string, unknown> = {
        id: originalData.id,
        tenantId,
        studentId: originalData.studentId,
        groupId: originalData.groupId ?? null,
        month: originalData.month,
        amountDue: originalData.amountDue,
        amountPaid: originalData.amountPaid,
        discountPercent: originalData.discountPercent ?? 0,
        status: originalData.status,
        paidAt: originalData.paidAt ?? null,
        note: originalData.note ?? null,
        createdAt: originalData.createdAt,
        updatedAt: originalData.updatedAt,
      };
      const { error: insertError } = await supabase.from("payments").insert(paymentRow);
      if (insertError) throw insertError;

      if (originalData._cashMovements && Array.isArray(originalData._cashMovements)) {
        for (const cm of originalData._cashMovements) {
          const { data: existingCm } = await supabase
            .from("cash_movements")
            .select("id")
            .eq("id", cm.id)
            .single();
          if (!existingCm) {
            await supabase.from("cash_movements").insert({
              id: cm.id,
              tenantId,
              userId: cm.userId,
              type: cm.type,
              category: cm.category,
              amount: cm.amount,
              description: cm.description,
              paymentMethod: cm.paymentMethod,
              date: cm.date,
              referenceId: cm.referenceId,
              autoGenerated: cm.autoGenerated ? 1 : 0,
              createdAt: cm.createdAt,
              updatedAt: cm.updatedAt,
            });
          }
        }
      }

      if (Number(originalData.amountPaid) > Number(originalData.amountDue)) {
        const excess = Number(originalData.amountPaid) - Number(originalData.amountDue);
        const { data: studentData } = await supabase
          .from("students")
          .select("advanceBalance")
          .eq("id", originalData.studentId)
          .single();
        const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
        await supabase
          .from("students")
          .update({ advanceBalance: currentAdvance + excess })
          .eq("id", originalData.studentId);
      }
    } else if (item.sourceType === "cash_movement") {
      const { data: existingCm } = await supabase
        .from("cash_movements")
        .select("id")
        .eq("id", originalData.id)
        .single();

      if (existingCm) {
        await supabase.from("deleted_items").delete().eq("id", id);
        return NextResponse.json({ success: true, warning: "Movement already exists" });
      }

      const cmRow: Record<string, unknown> = {
        id: originalData.id,
        tenantId,
        userId: originalData.userId,
        type: originalData.type,
        category: originalData.category,
        amount: originalData.amount,
        description: originalData.description,
        paymentMethod: originalData.paymentMethod,
        date: originalData.date,
        referenceId: originalData.referenceId ?? null,
        autoGenerated: originalData.autoGenerated ? 1 : 0,
        createdAt: originalData.createdAt,
        updatedAt: originalData.updatedAt,
      };
      const { error: insertError } = await supabase.from("cash_movements").insert(cmRow);
      if (insertError) throw insertError;

      if (originalData._payment && originalData.autoGenerated && originalData.referenceId) {
        const p = originalData._payment;
        const { data: existingPayment } = await supabase
          .from("payments")
          .select("id")
          .eq("id", p.id)
          .single();

        if (!existingPayment) {
          await supabase.from("payments").insert({
            id: p.id,
            tenantId,
            studentId: p.studentId,
            groupId: p.groupId ?? null,
            month: p.month,
            amountDue: p.amountDue,
            amountPaid: p.amountPaid,
            discountPercent: p.discountPercent ?? 0,
            status: p.status,
            paidAt: p.paidAt ?? null,
            note: p.note ?? null,
            createdAt: p.createdAt,
            updatedAt: p.updatedAt,
          });

          if (p._cashMovements && Array.isArray(p._cashMovements)) {
            for (const linkedCm of p._cashMovements) {
              const { data: exists } = await supabase
                .from("cash_movements")
                .select("id")
                .eq("id", linkedCm.id)
                .single();
              if (!exists) {
                await supabase.from("cash_movements").insert({
                  id: linkedCm.id,
                  tenantId,
                  userId: linkedCm.userId,
                  type: linkedCm.type,
                  category: linkedCm.category,
                  amount: linkedCm.amount,
                  description: linkedCm.description,
                  paymentMethod: linkedCm.paymentMethod,
                  date: linkedCm.date,
                  referenceId: linkedCm.referenceId,
                  autoGenerated: linkedCm.autoGenerated ? 1 : 0,
                  createdAt: linkedCm.createdAt,
                  updatedAt: linkedCm.updatedAt,
                });
              }
            }
          }

          if (Number(p.amountPaid) > Number(p.amountDue)) {
            const excess = Number(p.amountPaid) - Number(p.amountDue);
            const { data: sd } = await supabase
              .from("students")
              .select("advanceBalance")
              .eq("id", p.studentId)
              .single();
            const cur = Number((sd as any)?.advanceBalance || 0);
            await supabase
              .from("students")
              .update({ advanceBalance: cur + excess })
              .eq("id", p.studentId);
          }
        }
      }
    }

    await supabase.from("deleted_items").delete().eq("id", id);
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Failed to restore item" }, { status: 500 });
  }
}
