import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";
import { resetSessionCreditsOnPaymentDelete } from "@/lib/payments/utils";
import { moveToTrashMovement } from "@/lib/trash";

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { id } = await params;
    const body = await req.json();

    const { data: existing } = await supabase
      .from("cash_movements")
      .select("*")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (!existing) {
      return NextResponse.json({ error: "Movement not found" }, { status: 404 });
    }

    if (existing.autoGenerated) {
      return NextResponse.json(
        { error: "This transaction is auto-generated. Edit it through the Payments module." },
        { status: 400 }
      );
    }

    const updates: Record<string, unknown> = {};
    if (body.amount !== undefined) updates.amount = Number(body.amount);
    if (body.category !== undefined) updates.category = body.category;
    if (body.description !== undefined) updates.description = body.description;
    if (body.date !== undefined) updates.date = body.date;
    if (body.paymentMethod !== undefined) updates.paymentMethod = body.paymentMethod;

    const { data: updated, error } = await supabase
      .from("cash_movements")
      .update(updates)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(updated);
  } catch {
    return NextResponse.json({ error: "Failed to update cash movement" }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase, userId } = await getTenantContext();
    const { id } = await params;

    const { data: existing } = await supabase
      .from("cash_movements")
      .select("*")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (!existing) {
      return NextResponse.json({ error: "Movement not found" }, { status: 404 });
    }

    if (existing.autoGenerated && existing.referenceId) {
      const { data: payment } = await supabase
        .from("payments")
        .select("*")
        .eq("id", existing.referenceId)
        .eq("tenantId", tenantId)
        .single();

      if (payment) {
        const { data: linkedMovements } = await supabase
          .from("cash_movements")
          .select("*")
          .eq("referenceId", payment.id)
          .eq("autoGenerated", true);

        await moveToTrashMovement(supabase, tenantId, userId, existing, payment, linkedMovements || []);

        if (Number(payment.amountPaid) > Number(payment.amountDue)) {
          const excess = Number(payment.amountPaid) - Number(payment.amountDue);
          const { data: studentData } = await supabase
            .from("students")
            .select("advanceBalance")
            .eq("id", payment.studentId)
            .single();
          const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
          await supabase
            .from("students")
            .update({ advanceBalance: Math.max(0, currentAdvance - excess) })
            .eq("id", payment.studentId);
        }

        await supabase.from("cash_movements").delete().eq("referenceId", payment.id).eq("autoGenerated", true);
        await supabase.from("payments").delete().eq("id", payment.id);
        await resetSessionCreditsOnPaymentDelete({ supabase, tenantId, studentId: payment.studentId, groupId: payment.groupId ?? null });
      } else {
        await moveToTrashMovement(supabase, tenantId, userId, existing);
        await supabase.from("cash_movements").delete().eq("id", id);
      }
    } else {
      await moveToTrashMovement(supabase, tenantId, userId, existing);
      await supabase.from("cash_movements").delete().eq("id", id);
    }

    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Failed to delete cash movement" }, { status: 500 });
  }
}
