import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function GET(req: NextRequest) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { searchParams } = new URL(req.url);
    const type = searchParams.get("type");
    const category = searchParams.get("category");
    const dateFrom = searchParams.get("from");
    const dateTo = searchParams.get("to");

    let query = supabase
      .from("cash_movements")
      .select("*")
      .eq("tenantId", tenantId)
      .order("date", { ascending: false })
      .order("createdAt", { ascending: false })
      .limit(500);

    if (type) query = query.eq("type", type);
    if (category) query = query.eq("category", category);
    if (dateFrom) query = query.gte("date", dateFrom);
    if (dateTo) query = query.lte("date", dateTo);

    const { data: movements } = await query;

    const { data: totals } = await supabase
      .from("cash_movements")
      .select("type, amount")
      .eq("tenantId", tenantId);

    const income = (totals || [])
      .filter((m: any) => m.type === "income")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);
    const expense = (totals || [])
      .filter((m: any) => m.type === "expense")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);

    const now = new Date();
    const firstOfMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
    const lastOfMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

    const { data: monthMovements } = await supabase
      .from("cash_movements")
      .select("type, amount")
      .eq("tenantId", tenantId)
      .gte("date", firstOfMonth)
      .lte("date", lastOfMonth);

    const monthIncome = (monthMovements || [])
      .filter((m: any) => m.type === "income")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);
    const monthExpense = (monthMovements || [])
      .filter((m: any) => m.type === "expense")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);

    return NextResponse.json({
      movements: movements || [],
      balance: income - expense,
      totalIncome: income,
      totalExpense: expense,
      monthIncome,
      monthExpense,
      monthBalance: monthIncome - monthExpense,
    });
  } catch {
    return NextResponse.json({ error: "Failed to fetch cash movements" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { tenantId, userId, supabase } = await getTenantContext();
    const body = await req.json();
    const { type, category, amount, description, paymentMethod, date } = body;

    if (!type || !amount) {
      return NextResponse.json({ error: "Type and amount are required" }, { status: 400 });
    }

    const { data: movement, error } = await supabase
      .from("cash_movements")
      .insert({
        id: crypto.randomUUID(),
        tenantId,
        userId,
        type,
        category: category || "general",
        amount: Number(amount),
        description: description || null,
        paymentMethod: paymentMethod || "cash",
        date: date || new Date().toISOString().split("T")[0],
        autoGenerated: false,
      })
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(movement, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Failed to create cash movement" }, { status: 500 });
  }
}
