import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function GET(req: NextRequest) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { searchParams } = new URL(req.url);
    const type = searchParams.get("type");
    const category = searchParams.get("category");
    const dateFrom = searchParams.get("from");
    const dateTo = searchParams.get("to");

    const page = Math.max(1, parseInt(searchParams.get("page") || "1", 10) || 1);
    const limit = Math.min(500, Math.max(1, parseInt(searchParams.get("limit") || "100", 10) || 100));
    const offset = (page - 1) * limit;
    const hasPagination = searchParams.get("page") !== null || searchParams.get("limit") !== null;

    let query = supabase
      .from("cash_movements")
      .select("*")
      .eq("tenantId", tenantId)
      .order("date", { ascending: false })
      .order("createdAt", { ascending: false });
    if (hasPagination) query = (query as any).range(offset, offset + limit - 1);
    else query = query.limit(500);

    if (type) query = query.eq("type", type);
    if (category) query = query.eq("category", category);
    if (dateFrom) query = query.gte("date", dateFrom);
    if (dateTo) query = query.lte("date", dateTo);

    const { data: movements } = await query;

    const { cashMovementStats } = await import("@/lib/db/aggregates");
    const stats = await cashMovementStats(tenantId);
    const income = stats.totalIncome;
    const expense = stats.totalExpense;

    const monthIncome = (movements || [])
      .filter((m: any) => m.type === "income")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);
    const monthExpense = (movements || [])
      .filter((m: any) => m.type === "expense")
      .reduce((sum: number, m: any) => sum + Number(m.amount), 0);

    return NextResponse.json({
      movements: movements || [],
      balance: income - expense,
      totalIncome: income,
      totalExpense: expense,
      monthIncome,
      monthExpense,
      monthBalance: monthIncome - monthExpense,
    });
  } catch {
    return NextResponse.json({ error: "Failed to fetch cash movements" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { tenantId, userId, supabase } = await getTenantContext();
    const body = await req.json();
    const { type, category, amount, description, paymentMethod, date } = body;

    if (!type || !amount) {
      return NextResponse.json({ error: "Type and amount are required" }, { status: 400 });
    }

    const { data: movement, error } = await supabase
      .from("cash_movements")
      .insert({
        id: crypto.randomUUID(),
        tenantId,
        userId,
        type,
        category: category || "general",
        amount: Number(amount),
        description: description || null,
        paymentMethod: paymentMethod || "cash",
        date: date || new Date().toISOString().split("T")[0],
        autoGenerated: false,
      })
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(movement, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Failed to create cash movement" }, { status: 500 });
  }
}
