import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";
import { calculateStatus, normalizePayment, resetSessionCreditsOnPaymentDelete } from "@/lib/payments/utils";
import { moveToTrashPayment } from "@/lib/trash";

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { id } = await params;

    const { data: payment } = await supabase
      .from("payments")
      .select("*, students(id, fullName, monthlyFee, group_students(*, groups(name)))")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (!payment) {
      return NextResponse.json({ error: "Payment not found" }, { status: 404 });
    }
    return NextResponse.json(normalizePayment(payment));
  } catch {
    return NextResponse.json({ error: "Failed to fetch payment" }, { status: 500 });
  }
}

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase, userId } = await getTenantContext();
    const { id } = await params;
    const body = await req.json();

    const { data: existing } = await supabase
      .from("payments")
      .select("*, students(id, fullName)")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (!existing) {
      return NextResponse.json({ error: "Payment not found" }, { status: 404 });
    }

    const amountPaid = body.amountPaid !== undefined ? Number(body.amountPaid) : Number(existing.amountPaid);
    const status = calculateStatus(Number(existing.amountDue), amountPaid, new Date(existing.month));
    // Keep an already-recorded payment date; otherwise record one as soon as money
    // has actually been received (even for partial payments). The body can still
    // override with an explicit value when provided.
    const paidAt = "paidAt" in body
      ? body.paidAt
      : existing.paidAt || (amountPaid > 0 ? new Date().toISOString() : existing.paidAt);

    const oldAmountPaid = Number(existing.amountPaid);
    const newPayment = amountPaid - oldAmountPaid;

    const updateFields: Record<string, unknown> = {
      amountPaid,
      status,
      paidAt,
      groupId: "groupId" in body ? body.groupId : existing.groupId ?? null,
      note: "note" in body ? body.note : existing.note,
      updatedAt: new Date().toISOString(),
    };

    const { data: updated, error: updateError } = await supabase
      .from("payments")
      .update(updateFields)
      .eq("id", id)
      .select("*, students(id, fullName, monthlyFee, group_students(*, groups(name)))")
      .single();

    if (updateError || !updated) {
      return NextResponse.json(
        { error: updateError?.message || "Failed to update payment" },
        { status: 500 }
      );
    }

    if (newPayment > 0) {
      await supabase.from("cash_movements").insert({
        id: crypto.randomUUID(),
        tenantId,
        userId,
        type: "income",
        category: "Paiement",
        amount: newPayment,
        description: `Paiement - ${(existing.students as any)?.fullName || "Élève"}`,
        paymentMethod: "cash",
        date: new Date().toISOString().split("T")[0],
        referenceId: id,
        autoGenerated: true,
      }).maybeSingle();
    } else if (newPayment < 0) {
      const studentName = (existing.students as any)?.fullName || "Élève";
      await supabase.from("cash_movements").insert({
        id: crypto.randomUUID(),
        tenantId,
        userId,
        type: "expense",
        category: "Paiement",
        amount: Math.abs(newPayment),
        description: `Annulation paiement - ${studentName}`,
        paymentMethod: "cash",
        date: new Date().toISOString().split("T")[0],
        referenceId: id,
        autoGenerated: true,
      }).maybeSingle();
    }

    // Handle overpayments: compute net change in excess
    const oldExcess = Math.max(0, oldAmountPaid - Number(existing.amountDue));
    const newExcess = Math.max(0, amountPaid - Number(existing.amountDue));
    if (newExcess !== oldExcess) {
      const diff = newExcess - oldExcess;
      const { data: studentData } = await supabase.from("students").select("advanceBalance").eq("id", existing.studentId).single();
      const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
      await supabase.from("students").update({ advanceBalance: Math.max(0, currentAdvance + diff) }).eq("id", existing.studentId);
    }

    return NextResponse.json(normalizePayment(updated));
  } catch {
    return NextResponse.json({ error: "Failed to update payment" }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { tenantId, supabase, userId, email } = await getTenantContext();
    const { id } = await params;

    const { data: existing } = await supabase
      .from("payments")
      .select("*, students(fullName)")
      .eq("id", id)
      .eq("tenantId", tenantId)
      .single();

    if (!existing) {
      return NextResponse.json({ error: "Payment not found" }, { status: 404 });
    }

    const { data: linkedMovements } = await supabase
      .from("cash_movements")
      .select("*")
      .eq("referenceId", id)
      .eq("autoGenerated", true);

    await moveToTrashPayment(supabase, tenantId, userId, existing, linkedMovements || []);

    await supabase.from("cash_movements").delete().eq("referenceId", id).eq("autoGenerated", true);

    if (Number(existing.amountPaid) > Number(existing.amountDue)) {
      const excess = Number(existing.amountPaid) - Number(existing.amountDue);
      const { data: studentData } = await supabase
        .from("students")
        .select("advanceBalance")
        .eq("id", existing.studentId)
        .single();
      const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
      await supabase.from("students").update({ advanceBalance: Math.max(0, currentAdvance - excess) }).eq("id", existing.studentId);
    }

    await supabase.from("payments").delete().eq("id", id);

    await resetSessionCreditsOnPaymentDelete({ supabase, tenantId, studentId: existing.studentId, groupId: existing.groupId ?? null });

    const s = existing.students as unknown as { fullName?: string } | undefined;
    const studentName = s?.fullName ?? "Unknown";
    await supabase.from("audit_logs").insert({
      id: crypto.randomUUID(),
      tenantId,
      userId,
      action: "payment_deleted",
      entityType: "payment",
      entityId: id,
      metadata: {
        amountDue: existing.amountDue,
        amountPaid: existing.amountPaid,
        month: existing.month,
        studentName,
        deletedBy: email,
      },
    });

    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Failed to delete payment" }, { status: 500 });
  }
}
