"use client";

import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { useT, useI18n } from "@/lib/i18n";
import { formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter,
} from "@/components/ui/dialog";
import { Card, CardContent } from "@/components/ui/card";
import { Plus, ArrowUpRight, ArrowDownRight, Wallet, RefreshCw, Pencil, Trash2, Lock, Eye, EyeOff, Search, ChevronLeft, ChevronRight, FileText } from "lucide-react";
import { toast } from "sonner";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas-pro";

interface CashMovement {
  id: string;
  type: "income" | "expense";
  category: string;
  amount: number;
  description: string | null;
  paymentMethod: string;
  date: string;
  autoGenerated: boolean;
  referenceId?: string | null;
  createdAt: string;
}

interface CaisseData {
  movements: CashMovement[];
  balance: number;
  totalIncome: number;
  totalExpense: number;
  monthIncome: number;
  monthExpense: number;
  monthBalance: number;
}

export default function CaissePage() {
  const t = useT();
  const { direction } = useI18n();
  const align = direction === "rtl" ? "right" : "left";
  const [data, setData] = useState<CaisseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState<string>("");
  const [filterDay, setFilterDay] = useState<string>("");
  const [allTime, setAllTime] = useState(false);
  const [viewMonth, setViewMonth] = useState<string>(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  });
  const [search, setSearch] = useState("");
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [showBatchEdit, setShowBatchEdit] = useState(false);
  const [showBatchDelete, setShowBatchDelete] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [showPinDialog, setShowPinDialog] = useState(false);
  const [pinValue, setPinValue] = useState("");
  const [pinError, setPinError] = useState(false);

  const handleReveal = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const res = await fetch("/api/auth/verify-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ password: pinValue }),
      });
      if (res.ok) {
        setRevealed(true);
        setPinValue("");
        setPinError(false);
        setShowPinDialog(false);
      } else {
        setPinError(true);
      }
    } catch {
      setPinError(true);
    }
  };

    function changeMonth(delta: number) {
    setViewMonth((prev) => {
      const [y, m] = prev.split("-").map(Number);
      const d = new Date(y, m - 1 + delta, 1);
      return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    });
  }

  const loadData = useCallback(async () => {
    setLoading(true);
    const params = new URLSearchParams();
    if (filterType) params.set("type", filterType);
    if (filterDay) {
      params.set("from", filterDay);
      params.set("to", filterDay);
    } else if (!allTime) {
      const [y, m] = viewMonth.split("-").map(Number);
      const firstOfMonth = `${y}-${String(m).padStart(2, "0")}-01`;
      const lastOfMonth = `${y}-${String(m).padStart(2, "0")}-${new Date(y, m, 0).getDate()}`;
      params.set("from", firstOfMonth);
      params.set("to", lastOfMonth);
    }
    const res = await fetch(`/api/caisse?${params.toString()}`);
    if (res.ok) setData(await res.json());
    setLoading(false);
  }, [filterType, viewMonth, allTime, filterDay]);

  useEffect(() => { loadData(); }, [loadData]);

  const [printing, setPrinting] = useState(false);
  const [pdfViewerUrl, setPdfViewerUrl] = useState<string | null>(null);
  const pdfViewerUrlRef = useRef<string | null>(null);
  const PAGE_SIZE = 50;
  const [page, setPage] = useState(1);

  function buildCaisseInvoiceHtml(m: CashMovement, i: number): string {
    const raw = m.createdAt ? new Date(m.createdAt) : new Date(m.date);
    const isMidnight = raw.getHours() === 0 && raw.getMinutes() === 0 && raw.getSeconds() === 0;
    const dateObj = !isMidnight ? raw : new Date();
    const dateLabel = dateObj.toLocaleString("ar-DZ", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
    const typeLabel = m.type === "income" ? "مدخول" : "مصروف";
    const typeColor = m.type === "income" ? "#16a34a" : "#dc2626";
    const cat = (CATEGORY_KEYS[m.category] ? t(CATEGORY_KEYS[m.category]) : m.category) || "—";
    const method = (METHOD_KEYS[m.paymentMethod] ? t(METHOD_KEYS[m.paymentMethod]) : m.paymentMethod) || "—";
    const desc = translateDescription(t, m.description);
    return `
      <div id="caisse-inv-${i}" dir="rtl" style="width:350px;margin:0 auto 20px;padding:24px;font-family:'Segoe UI',Arial,sans-serif;background:#fff;direction:rtl;text-align:right;border:1px solid #e2e8f0;border-radius:8px;">
        <h2 style="text-align:center;font-size:18px;font-weight:700;margin:0 0 8px;color:#1e293b;">فاتورة الصندوق</h2>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:0 0 16px;" />
        <table style="width:100%;font-size:13px;border-collapse:collapse;">
          <tr><td style="padding:3px 0;color:#475569;">التاريخ:</td><td style="padding:3px 0;font-weight:600;text-align:left;">${dateLabel}</td></tr>
          <tr><td style="padding:3px 0;color:#475569;">النوع:</td><td style="padding:3px 0;font-weight:600;text-align:left;color:${typeColor};">${typeLabel}</td></tr>
          <tr><td style="padding:3px 0;color:#475569;">الفئة:</td><td style="padding:3px 0;font-weight:600;text-align:left;">${cat}</td></tr>
          <tr><td style="padding:3px 0;color:#475569;">طريقة الدفع:</td><td style="padding:3px 0;font-weight:600;text-align:left;">${method}</td></tr>
          <tr><td style="padding:3px 0;color:#475569;">الوصف:</td><td style="padding:3px 0;font-weight:600;text-align:left;">${desc}</td></tr>
          ${m.autoGenerated ? `<tr><td colspan="2" style="padding:6px 0 0;color:#d97706;font-size:11px;text-align:center;">${t("caisse.auto_generated_hint")}</td></tr>` : ""}
        </table>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:12px 0;" />
        <table style="width:100%;font-size:13px;border-collapse:collapse;">
          <thead><tr style="background:#f1f5f9;"><th style="padding:6px 8px;text-align:right;">البيان</th><th style="padding:6px 8px;text-align:left;">المبلغ</th></tr></thead>
          <tbody>
            <tr><td style="padding:8px;font-weight:600;">${typeLabel}</td><td style="padding:8px;text-align:left;font-weight:700;color:${typeColor};">${m.type === "income" ? "+" : "-"}${formatCurrency(m.amount)}</td></tr>
          </tbody>
        </table>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:16px 0 8px;" />
        <p style="text-align:center;font-size:11px;color:#64748b;margin:0;">شكراً لكم</p>
      </div>
    `;
  }

  async function handlePrintCaisseInvoice(m: CashMovement) {
    setPrinting(true);
    let container: HTMLDivElement | null = null;
    let fallbackTimer: ReturnType<typeof setTimeout> | null = null;
    try {
      container = document.createElement("div");
      container.style.cssText = "position:fixed;left:-9999px;top:0;z-index:-1;pointer-events:none;";
      container.innerHTML = buildCaisseInvoiceHtml(m, 0);
      document.body.appendChild(container);
      fallbackTimer = setTimeout(() => container?.remove(), 5000);
      await new Promise((r) => setTimeout(r, 300));
      const el = document.getElementById("caisse-inv-0");
      if (!el) { toast.error("خطأ في إنشاء الفاتورة"); return; }
      const canvas = await html2canvas(el, { scale: 3, backgroundColor: "#ffffff", useCORS: true, logging: false });
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" });
      const imgData = canvas.toDataURL("image/png");
      const ratio = pdf.internal.pageSize.getWidth() / canvas.width;
      pdf.addImage(imgData, "PNG", 0, 0, pdf.internal.pageSize.getWidth(), canvas.height * ratio);
      if (pdfViewerUrlRef.current) URL.revokeObjectURL(pdfViewerUrlRef.current);
      const url = URL.createObjectURL(pdf.output("blob"));
      pdfViewerUrlRef.current = url;
      setPdfViewerUrl(url);
    } catch (e) {
      console.error("Caisse invoice PDF error:", e);
      toast.error("فشل إنشاء الفاتورة");
    } finally {
      if (fallbackTimer) clearTimeout(fallbackTimer);
      if (container && container.parentElement) container.remove();
      else document.getElementById("caisse-inv-0")?.parentElement?.remove();
      setPrinting(false);
    }
  }

  function buildDailyCaisseHtml(day: string, movements: CashMovement[], income: number, expense: number, balance: number): string {
    const dayLabel = new Date(day).toLocaleDateString("ar-DZ", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
    const rows = movements.map((m) => {
      const cat = (CATEGORY_KEYS[m.category] ? t(CATEGORY_KEYS[m.category]) : m.category) || "—";
      const method = (METHOD_KEYS[m.paymentMethod] ? t(METHOD_KEYS[m.paymentMethod]) : m.paymentMethod) || "—";
      const typeLabel = m.type === "income" ? "مدخول" : "مصروف";
      const amountStr = (m.type === "income" ? "+" : "-") + formatCurrency(m.amount);
      const color = m.type === "income" ? "#16a34a" : "#dc2626";
      const desc = translateDescription(t, m.description);
      return `<tr><td style="padding:6px 8px;text-align:right;font-size:11px;">${cat}</td><td style="padding:6px 8px;text-align:right;font-size:11px;">${desc}</td><td style="padding:6px 8px;text-align:left;font-size:11px;color:${color};font-weight:600;">${amountStr}</td><td style="padding:6px 8px;text-align:right;font-size:10px;color:#64748b;">${method}</td><td style="padding:6px 8px;text-align:right;font-size:10px;color:${color};">${typeLabel}</td></tr>`;
    }).join("");
    return `
      <div id="caisse-daily" dir="rtl" style="width:650px;margin:0 auto;padding:24px;font-family:'Segoe UI',Arial,sans-serif;background:#fff;direction:rtl;text-align:right;border:1px solid #e2e8f0;border-radius:8px;">
        <h2 style="text-align:center;font-size:18px;font-weight:700;margin:0 0 4px;color:#1e293b;">فاتورة الصندوق اليومية</h2>
        <p style="text-align:center;font-size:12px;color:#64748b;margin:0 0 12px;">${dayLabel} — ${day}</p>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:0 0 16px;" />
        <table style="width:100%;font-size:12px;border-collapse:collapse;">
          <thead><tr style="background:#f1f5f9;"><th style="padding:7px 8px;text-align:right;">الفئة</th><th style="padding:7px 8px;text-align:right;">الوصف</th><th style="padding:7px 8px;text-align:left;">المبلغ</th><th style="padding:7px 8px;text-align:right;">طريقة الدفع</th><th style="padding:7px 8px;text-align:right;">النوع</th></tr></thead>
          <tbody>${rows || `<tr><td colspan="5" style="padding:12px;text-align:center;color:#64748b;">لا توجد حركات في هذا اليوم</td></tr>`}</tbody>
        </table>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:16px 0;" />
        <table style="width:100%;font-size:13px;border-collapse:collapse;">
          <tr><td style="padding:5px 8px;color:#475569;">إجمالي المداخيل:</td><td style="padding:5px 8px;text-align:left;font-weight:700;color:#16a34a;">+${formatCurrency(income)}</td></tr>
          <tr><td style="padding:5px 8px;color:#475569;">إجمالي المخارج:</td><td style="padding:5px 8px;text-align:left;font-weight:700;color:#dc2626;">-${formatCurrency(expense)}</td></tr>
          <tr style="background:#f8fafc;"><td style="padding:7px 8px;font-weight:700;">الرصيد اليومي:</td><td style="padding:7px 8px;text-align:left;font-weight:800;color:${balance >= 0 ? "#16a34a" : "#dc2626"};">${formatCurrency(balance)}</td></tr>
          <tr><td style="padding:5px 8px;color:#475569;font-size:11px;">عدد الحركات:</td><td style="padding:5px 8px;text-align:left;font-size:11px;">${movements.length}</td></tr>
        </table>
        <hr style="border:none;border-top:1px solid #cbd5e1;margin:16px 0 8px;" />
        <p style="text-align:center;font-size:11px;color:#64748b;margin:0;">شكراً لكم — ${new Date().toLocaleString("ar-DZ")}</p>
      </div>
    `;
  }

  async function handlePrintDaily() {
    if (!filterDay) { toast.error("اختر يوماً أولاً"); return; }
    if (!dailyStats || dailyStats.movements.length === 0) { toast.error("لا توجد حركات في هذا اليوم"); return; }
    setPrinting(true);
    let container: HTMLDivElement | null = null;
    let fallbackTimer: ReturnType<typeof setTimeout> | null = null;
    try {
      container = document.createElement("div");
      container.style.cssText = "position:fixed;left:-9999px;top:0;z-index:-1;pointer-events:none;";
      container.innerHTML = buildDailyCaisseHtml(filterDay, dailyStats.movements, dailyStats.income, dailyStats.expense, dailyStats.balance);
      document.body.appendChild(container);
      fallbackTimer = setTimeout(() => container?.remove(), 8000);
      await new Promise((r) => setTimeout(r, 300));
      const el = document.getElementById("caisse-daily");
      if (!el) { toast.error("خطأ في إنشاء الفاتورة"); return; }
      const canvas = await html2canvas(el, { scale: 2, backgroundColor: "#ffffff", useCORS: true, logging: false });
      const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
      const imgData = canvas.toDataURL("image/png");
      const ratio = pdf.internal.pageSize.getWidth() / canvas.width;
      const h = canvas.height * ratio;
      pdf.addImage(imgData, "PNG", 0, 0, pdf.internal.pageSize.getWidth(), h);
      if (pdfViewerUrlRef.current) URL.revokeObjectURL(pdfViewerUrlRef.current);
      const url = URL.createObjectURL(pdf.output("blob"));
      pdfViewerUrlRef.current = url;
      setPdfViewerUrl(url);
    } catch (e) {
      console.error("Daily PDF error:", e);
      toast.error("فشل إنشاء فاتورة اليوم");
    } finally {
      if (fallbackTimer) clearTimeout(fallbackTimer);
      if (container && container.parentElement) container.remove();
      else document.getElementById("caisse-daily")?.remove();
      setPrinting(false);
    }
  }

  const filteredMovements = useMemo(() => (data?.movements ?? []).filter((m) => {
    if (filterDay && m.date !== filterDay) return false;
    if (!search.trim()) return true;
    const q = search.trim().toLowerCase();
    const category = translateDescription(t, m.category) + " " + m.category;
    const method = METHOD_KEYS[m.paymentMethod] ? t(METHOD_KEYS[m.paymentMethod]) : m.paymentMethod;
    return [m.description, category, method, m.id]
      .filter(Boolean)
      .some((v) => v!.toLowerCase().includes(q));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }), [data?.movements, search, filterDay, t]);

  const dailyStats = useMemo(() => {
    if (!filterDay || !data?.movements) return null;
    const dayMovs = data.movements.filter((m) => m.date === filterDay);
    const income = dayMovs.filter((m) => m.type === "income").reduce((s, m) => s + m.amount, 0);
    const expense = dayMovs.filter((m) => m.type === "expense").reduce((s, m) => s + m.amount, 0);
    return { count: dayMovs.length, income, expense, balance: income - expense, movements: dayMovs };
  }, [filterDay, data?.movements]);

  useEffect(() => { setPage(1); }, [search, filterType, allTime, viewMonth, filterDay]);
  const totalPages = Math.max(1, Math.ceil(filteredMovements.length / PAGE_SIZE));
  const paginatedMovements = useMemo(() => filteredMovements.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE), [filteredMovements, page]);
  useEffect(() => { if (page > totalPages) setPage(totalPages); }, [totalPages, page]);

  return (
    <div className="space-y-6 p-4 md:p-6" dir={direction}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <h1 className="text-2xl font-bold">{t("caisse.title")}</h1>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => { setRevealed(false); loadData(); }}>
            <RefreshCw className="size-4" />
          </Button>
          <NewMovementDialog onCreated={loadData} />
        </div>
      </div>

      {/* Balance Card */}
      <Card className="bg-gradient-to-r from-primary/10 to-primary/5">
        <CardContent className="p-6">
          <div className="flex items-center gap-3">
            <Wallet className="size-8 text-primary" />
            <div className="flex-1">
              <p className="text-sm text-muted-foreground">{t("caisse.balance")}</p>
              <p className={`text-3xl font-bold ${(data?.balance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
                {revealed ? formatCurrency(data?.balance ?? 0) : "••••••"}
              </p>
            </div>
            {!revealed ? (
              <Button variant="outline" size="sm" onClick={() => setShowPinDialog(true)}>
                <Lock className="size-4" /> {t("caisse.reveal")}
              </Button>
            ) : (
              <Button variant="outline" size="sm" onClick={() => setRevealed(false)}>
                <EyeOff className="size-4" /> {t("caisse.hide")}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Monthly Summary */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_income")}</p>
            <p className="text-xl font-bold text-green-600">{revealed ? formatCurrency(data?.monthIncome ?? 0) : "••••••"}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_expense")}</p>
            <p className="text-xl font-bold text-red-600">{revealed ? formatCurrency(data?.monthExpense ?? 0) : "••••••"}</p>
          </CardContent>
        </Card>
        <Card className="col-span-2 sm:col-span-1">
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_balance")}</p>
            <p className={`text-xl font-bold ${(data?.monthBalance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
              {revealed ? formatCurrency(data?.monthBalance ?? 0) : "••••••"}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* PIN Dialog */}
      <Dialog open={showPinDialog} onOpenChange={setShowPinDialog}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>{t("caisse.pin_required")}</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleReveal} className="space-y-4">
            <Input
              type="password"
              value={pinValue}
              onChange={(e) => { setPinValue(e.target.value); setPinError(false); }}
              autoFocus
              autoComplete="off"
            />
            {pinError && <p className="text-sm text-destructive">{t("caisse.wrong_password")}</p>}
            <button
              type="button"
              className="text-xs text-primary underline"
              onClick={async () => {
                const input = prompt(t("settings.password_enter_default") || "أدخل كلمة المرور الافتراضية profmanager1234 للتأكيد:");
                if (input === null) return;
                if (input !== "profmanager1234") { toast.error(t("caisse.wrong_password")); return; }
                if (!confirm(t("settings.password_reset_confirm"))) return;
                const r = await fetch("/api/auth/reset-password", { method: "POST" });
                if (r.ok) { toast.success(t("settings.password_reset_success")); setPinValue(""); setPinError(false); } else toast.error(t("common.error"));
              }}
            >
              {t("settings.password_forgot")}
            </button>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => { setShowPinDialog(false); setPinValue(""); setPinError(false); }}>
                {t("common.cancel")}
              </Button>
              <Button type="submit"><Eye className="size-4 mr-1" /> {t("caisse.reveal")}</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 items-center">
        <div className="relative">
          <Search className="absolute start-2.5 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder={t("common.search")}
            className="w-56 ps-8"
          />
        </div>
        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className="px-3 py-2 border border-input rounded-md bg-background text-sm"
        >
          <option value="">{t("common.all")}</option>
          <option value="income">{t("caisse.income")}</option>
          <option value="expense">{t("caisse.expense")}</option>
        </select>
        <label className="flex cursor-pointer items-center gap-1.5 text-sm">
          <input
            type="checkbox"
            checked={allTime}
            onChange={(e) => setAllTime(e.target.checked)}
            className="size-4 accent-primary"
          />
          {t("caisse.all_time")}
        </label>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" onClick={() => changeMonth(-1)} title={t("payments.prev_month")} disabled={allTime || !!filterDay}>
            {direction === "rtl" ? <ChevronRight className="size-4" /> : <ChevronLeft className="size-4" />}
          </Button>
          <Input type="month" value={viewMonth} onChange={(e) => e.target.value && setViewMonth(e.target.value)} className="w-44" aria-label={t("payments.month")} disabled={allTime || !!filterDay} />
          <Button variant="outline" size="icon" onClick={() => changeMonth(1)} title={t("payments.next_month")} disabled={allTime || !!filterDay}>
            {direction === "rtl" ? <ChevronLeft className="size-4" /> : <ChevronRight className="size-4" />}
          </Button>
        </div>
        <div className="flex items-center gap-2">
          <Input type="date" value={filterDay} onChange={(e) => setFilterDay(e.target.value)} className="w-44" aria-label="تصفية باليوم" title="تصفية باليوم" />
          {filterDay && (
            <Button variant="ghost" size="sm" onClick={() => setFilterDay("")} title="إلغاء فلتر اليوم">
              ✕
            </Button>
          )}
          <Button variant="default" size="sm" onClick={handlePrintDaily} disabled={!filterDay || !dailyStats || dailyStats.count === 0 || printing} title="فاتورة اليوم">
            <FileText className="size-4 ml-1" /> فاتورة اليوم
          </Button>
        </div>
      </div>
      {filterDay && dailyStats && (
        <div className="rounded-lg border bg-muted/30 px-4 py-2 flex flex-wrap items-center gap-4 text-sm">
          <span>اليوم: <b>{filterDay}</b></span>
          <span className="text-green-600">مداخيل: <b>{revealed ? formatCurrency(dailyStats.income) : "••••"}</b></span>
          <span className="text-red-600">مخاريج: <b>{revealed ? formatCurrency(dailyStats.expense) : "••••"}</b></span>
          <span className={dailyStats.balance >= 0 ? "text-green-700" : "text-red-700"}>الرصيد: <b>{revealed ? formatCurrency(dailyStats.balance) : "••••"}</b></span>
          <span className="text-muted-foreground">الحركات: {dailyStats.count}</span>
        </div>
      )}

      {/* Selection toolbar */}
      {selectedIds.size > 0 && (
        <div className="flex flex-wrap items-center gap-2 rounded-lg border bg-muted/30 px-4 py-2">
          <span className="text-sm font-medium">{selectedIds.size} {t("caisse.selected")}</span>
          <div className="flex-1" />
          <Button variant="outline" size="sm" onClick={() => setShowBatchEdit(true)}>
            <Pencil className="size-4" /> {t("caisse.batch_edit")}
          </Button>
          <Button variant="destructive" size="sm" onClick={() => setShowBatchDelete(true)}>
            <Trash2 className="size-4" /> {t("caisse.batch_delete")}
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setSelectedIds(new Set())}>
            {t("common.cancel")}
          </Button>
        </div>
      )}

      {/* Movements Table */}
      {loading ? (
        <p className="text-center text-muted-foreground">{t("common.loading")}</p>
      ) : !filteredMovements.length ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">
            {t("caisse.no_movements")}
          </CardContent>
        </Card>
      ) : (
        <div className="overflow-x-auto rounded-lg border">
          <table className="w-full border-collapse" style={{ tableLayout: "fixed", minWidth: "960px" }}>
            <colgroup>
              <col style={{ width: "4%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "9%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "13%" }} />
              <col style={{ width: "27%" }} />
              <col style={{ width: "11%" }} />
            </colgroup>
            <thead>
              <tr className="bg-muted/50 border-b">
                <th style={{ textAlign: "center", padding: "12px" }}>
                  <input
                    type="checkbox"
                    className="size-4 accent-primary"
                    checked={filteredMovements.length > 0 && filteredMovements.every((m) => selectedIds.has(m.id))}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setSelectedIds(new Set(filteredMovements.map((m) => m.id)));
                      } else {
                        setSelectedIds(new Set());
                      }
                    }}
                  />
                </th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.date")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.type")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("payments.amount")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.category")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.payment_method")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.description")}</th>
                <th style={{ textAlign: "center", padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.actions")}</th>
              </tr>
            </thead>
            <tbody>
              {paginatedMovements.map((m, i) => (
                <MovementRow
                  key={m.id}
                  movement={m}
                  onUpdated={loadData}
                  zebra={i % 2 === 1}
                  selected={selectedIds.has(m.id)}
                  onSelect={(checked) => {
                    const next = new Set(selectedIds);
                    if (checked) next.add(m.id);
                    else next.delete(m.id);
                    setSelectedIds(next);
                  }}
                  onPrint={handlePrintCaisseInvoice}
                  printing={printing}
                />
              ))}
            </tbody>
          </table>
        </div>
      )}

      {filteredMovements.length > PAGE_SIZE && (
        <div className="flex items-center justify-between py-3 text-sm">
          <span className="text-muted-foreground">{page} / {totalPages} — {filteredMovements.length} {t("common.total")}</span>
          <div className="flex gap-1">
            <Button variant="outline" size="sm" onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1}>{t("common.previous")}</Button>
            <span className="px-2 text-xs flex items-center">{page} / {totalPages}</span>
            <Button variant="outline" size="sm" onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages}>{t("common.next")}</Button>
          </div>
        </div>
      )}

      {showBatchEdit && (
        <BatchEditDialog
          ids={[...selectedIds]}
          onClose={() => setShowBatchEdit(false)}
          onSaved={() => { setShowBatchEdit(false); setSelectedIds(new Set()); loadData(); }}
        />
      )}
      {showBatchDelete && (
        <BatchDeleteDialog
          ids={[...selectedIds]}
          onClose={() => setShowBatchDelete(false)}
          onDeleted={() => { setShowBatchDelete(false); setSelectedIds(new Set()); loadData(); }}
        />
      )}

      <Dialog open={!!pdfViewerUrl} onOpenChange={(o) => { if (!o) { setPdfViewerUrl(null); if (pdfViewerUrlRef.current) { URL.revokeObjectURL(pdfViewerUrlRef.current); pdfViewerUrlRef.current = null; } } }}>
        <DialogContent className="max-w-4xl h-[90vh] flex flex-col">
          <DialogHeader>
            <DialogTitle>{t("caisse.title")}</DialogTitle>
          </DialogHeader>
          {pdfViewerUrl && (
            <iframe src={pdfViewerUrl} className="w-full flex-1 min-h-0 border-0 rounded" style={{ height: "calc(90vh - 120px)" }} />
          )}
          <DialogFooter className="shrink-0">
            <Button variant="outline" onClick={() => { const a = document.createElement("a"); a.href = pdfViewerUrl!; a.download = "فاتورة-صندوق-" + new Date().toISOString().slice(0, 10) + ".pdf"; a.click(); }}>
              <FileText className="size-4 ml-1" /> {t("payments.download_pdf")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

const CATEGORY_KEYS: Record<string, string> = {
  Paiement: "caisse.category_payment",
  Inscription: "caisse.category_inscription",
  Vente: "caisse.category_sale",
  "Autre revenu": "caisse.category_other_income",
  Salaire: "caisse.category_salary",
  Loyer: "caisse.category_rent",
  "Électricité": "caisse.category_electricity",
  Fournitures: "caisse.category_supplies",
  Entretien: "caisse.category_maintenance",
  "Autre dépense": "caisse.category_other_expense",
  general: "caisse.category_general",
};

const METHOD_KEYS: Record<string, string> = {
  cash: "payments.cash",
  cheque: "payments.cheque",
  transfer: "payments.transfer",
  card: "payments.card",
};

function translateDescription(t: (k: string) => string, desc: string | null): string {
  if (!desc) return "—";
  return desc
    .replace(/^Paiement suppl\u00e9mentaire/, t("caisse.description_additional"))
    .replace(/^Paiement/, t("caisse.description_payment"))
    .replace(/^Annulation paiement/, t("caisse.description_cancellation"))
    .replace(/^Salaire enseignant/, t("caisse.description_salary"));
}

function MovementRow({ movement, onUpdated, zebra, selected, onSelect, onPrint, printing }: {
  movement: CashMovement;
  onUpdated: () => void;
  zebra: boolean;
  selected: boolean;
  onSelect: (checked: boolean) => void;
  onPrint: (m: CashMovement) => void;
  printing: boolean;
}) {
  const t = useT();
  const { direction } = useI18n();
  const align = direction === "rtl" ? "right" : "left";
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  const categoryLabel = CATEGORY_KEYS[movement.category]
    ? t(CATEGORY_KEYS[movement.category])
    : movement.category;
  const methodLabel = METHOD_KEYS[movement.paymentMethod]
    ? t(METHOD_KEYS[movement.paymentMethod])
    : movement.paymentMethod;
  const descriptionLabel = translateDescription(t, movement.description);

  return (
    <>
      <tr className={`border-b ${zebra ? "bg-muted/20" : "bg-background"}`}>
        <td style={{ padding: "12px", textAlign: "center" }}>
          <input
            type="checkbox"
            className="size-4 accent-primary"
            checked={selected}
            onChange={(e) => onSelect(e.target.checked)}
          />
        </td>
        <td style={{ padding: "12px", textAlign: align, fontWeight: 600, fontSize: "14px", color: "hsl(var(--foreground))" }}>
          {new Date(movement.date).toLocaleDateString()}
        </td>
        <td style={{ padding: "12px", textAlign: align }}>
          <span className={`inline-flex items-center gap-1 text-sm font-medium ${movement.type === "income" ? "text-green-600" : "text-red-600"}`}>
            {movement.type === "income" ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}
            {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
          </span>
        </td>
        <td style={{ padding: "12px", textAlign: align }}>
          <span className={`text-sm font-medium ${movement.type === "income" ? "text-green-600" : "text-red-600"}`}>
            {movement.type === "income" ? "+" : "-"}{formatCurrency(movement.amount)}
          </span>
        </td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--foreground))" }}>{categoryLabel}</td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--muted-foreground))" }}>{methodLabel}</td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--muted-foreground))", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{descriptionLabel}</td>
        <td style={{ padding: "12px", textAlign: "center" }}>
          <div className="flex items-center justify-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="size-8 text-purple-600 hover:text-purple-700"
              onClick={() => onPrint(movement)}
              disabled={printing}
              title="فاتورة"
            >
              <FileText className="size-4" />
            </Button>
            <div className="relative group">
              <Button
                variant="ghost"
                size="icon"
                className="size-8"
                disabled={movement.autoGenerated}
                onClick={() => setShowEdit(true)}
              >
                <Pencil className="size-4" />
              </Button>
              {movement.autoGenerated && (
                <div className="absolute bottom-full right-0 mb-1 hidden group-hover:block z-50">
                  <div className="bg-popover text-popover-foreground text-xs rounded-md px-3 py-1.5 shadow-md border whitespace-nowrap">
                    {t("caisse.auto_generated_hint")}
                  </div>
                </div>
              )}
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="size-8 text-destructive hover:text-destructive"
              onClick={() => setShowDelete(true)}
            >
              <Trash2 className="size-4" />
            </Button>
          </div>
        </td>
      </tr>

      {showEdit && (
        <EditMovementDialog
          movement={movement}
          onClose={() => setShowEdit(false)}
          onSaved={() => { setShowEdit(false); onUpdated(); }}
        />
      )}

      {showDelete && (
        <DeleteMovementDialog
          movement={movement}
          onClose={() => setShowDelete(false)}
          onDeleted={() => { setShowDelete(false); onUpdated(); }}
        />
      )}
    </>
  );
}

function EditMovementDialog({ movement, onClose, onSaved }: {
  movement: CashMovement;
  onClose: () => void;
  onSaved: () => void;
}) {
  const t = useT();
  const [amount, setAmount] = useState(String(movement.amount));
  const [category, setCategory] = useState(movement.category);
  const [description, setDescription] = useState(movement.description || "");
  const [date, setDate] = useState(movement.date);
  const [paymentMethod, setPaymentMethod] = useState(movement.paymentMethod);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch("/api/caisse/categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: Number(amount),
          category,
          description: description || null,
          date,
          paymentMethod,
        }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_updated"));
        onSaved();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.edit_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">{t("caisse.category_general")}</option>
              {categories.filter((c) => c.type === movement.type).map((c) => (
                <option key={c.name} value={c.name}>{CATEGORY_KEYS[c.name] ? t(CATEGORY_KEYS[c.name]) : c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.date")}</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function DeleteMovementDialog({ movement, onClose, onDeleted }: {
  movement: CashMovement;
  onClose: () => void;
  onDeleted: () => void;
}) {
  const t = useT();
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, { method: "DELETE" });
      if (res.ok) {
        toast.success(t("caisse.movement_deleted"));
        onDeleted();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>{t("caisse.delete_movement")}</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">{t("caisse.delete_confirm")}</p>
        <div className="rounded-md border p-3 space-y-1 text-sm">
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.date")}:</span>
            <span>{new Date(movement.date).toLocaleDateString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.type")}:</span>
            <span className={movement.type === "income" ? "text-green-600" : "text-red-600"}>
              {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("payments.amount")}:</span>
            <span className="font-medium">{formatCurrency(movement.amount)}</span>
          </div>
          {movement.autoGenerated && movement.referenceId && (
            <p className="text-xs text-amber-600 mt-2">{t("caisse.auto_generated_hint")} {t("caisse.delete_confirm")}</p>
          )}
        </div>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? t("common.deleting") : t("common.delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function NewMovementDialog({ onCreated }: { onCreated: () => void }) {
  const t = useT();
  const [open, setOpen] = useState(false);
  const [type, setType] = useState<"income" | "expense">("income");
  const [category, setCategory] = useState("general");
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);

  useEffect(() => {
    if (open) {
      fetch("/api/caisse/categories")
        .then((r) => r.json())
        .then(setCategories)
        .catch(() => {});
    }
  }, [open]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch("/api/caisse", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type, category, amount: Number(amount), description: description || undefined, paymentMethod }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_created"));
        setOpen(false);
        onCreated();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="sm"><Plus className="size-4" /> {t("caisse.new_movement")}</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.new_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-2">
            <Button type="button" variant={type === "income" ? "default" : "outline"} onClick={() => setType("income")} className="flex-1">
              {t("caisse.income")}
            </Button>
            <Button type="button" variant={type === "expense" ? "default" : "outline"} onClick={() => setType("expense")} className="flex-1">
              {t("caisse.expense")}
            </Button>
          </div>
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">{t("caisse.category_general")}</option>
              {categories.filter((c) => c.type === type).map((c) => (
                <option key={c.name} value={c.name}>{CATEGORY_KEYS[c.name] ? t(CATEGORY_KEYS[c.name]) : c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function BatchEditDialog({ ids, onClose, onSaved }: {
  ids: string[];
  onClose: () => void;
  onSaved: () => void;
}) {
  const t = useT();
  const [date, setDate] = useState("");
  const [category, setCategory] = useState("");
  const [description, setDescription] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("");
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);

  useEffect(() => {
    fetch("/api/caisse/categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const updates: Record<string, unknown> = {};
    if (date) updates.date = date;
    if (category) updates.category = category;
    if (description.trim()) updates.description = description.trim();
    if (paymentMethod) updates.paymentMethod = paymentMethod;
    if (Object.keys(updates).length === 0) return;
    setSaving(true);
    try {
      const res = await fetch("/api/caisse/batch", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids, updates }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_updated"));
        onSaved();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.batch_edit")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <p className="text-sm text-muted-foreground">{t("caisse.batch_edit_hint")}</p>
          <div className="space-y-2">
            <Label>{t("common.date")}</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="">{t("caisse.batch_keep")}</option>
              <option value="general">{t("caisse.category_general")}</option>
              {categories.map((c) => (
                <option key={c.name} value={c.name}>{CATEGORY_KEYS[c.name] ? t(CATEGORY_KEYS[c.name]) : c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="">{t("caisse.batch_keep")}</option>
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function BatchDeleteDialog({ ids, onClose, onDeleted }: {
  ids: string[];
  onClose: () => void;
  onDeleted: () => void;
}) {
  const t = useT();
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    try {
      const res = await fetch("/api/caisse/batch", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_deleted"));
        onDeleted();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>{t("caisse.batch_delete")}</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">{t("caisse.batch_delete_confirm", { count: ids.length })}</p>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? t("common.deleting") : t("common.delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
