"use client";

import { useState, useEffect, useCallback } from "react";
import { useT } from "@/lib/i18n";
import { formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter,
} from "@/components/ui/dialog";
import { Card, CardContent } from "@/components/ui/card";
import { Plus, ArrowUpRight, ArrowDownRight, Wallet, RefreshCw, Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";

interface CashMovement {
  id: string;
  type: "income" | "expense";
  category: string;
  amount: number;
  description: string | null;
  paymentMethod: string;
  date: string;
  autoGenerated: boolean;
  referenceId?: string | null;
  createdAt: string;
}

interface CaisseData {
  movements: CashMovement[];
  balance: number;
  totalIncome: number;
  totalExpense: number;
  monthIncome: number;
  monthExpense: number;
  monthBalance: number;
}

export default function CaissePage() {
  const t = useT();
  const [data, setData] = useState<CaisseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState<string>("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  const loadData = useCallback(async () => {
    setLoading(true);
    const params = new URLSearchParams();
    if (filterType) params.set("type", filterType);
    if (dateFrom) params.set("from", dateFrom);
    if (dateTo) params.set("to", dateTo);
    const res = await fetch(`/api/caisse?${params.toString()}`);
    if (res.ok) setData(await res.json());
    setLoading(false);
  }, [filterType, dateFrom, dateTo]);

  useEffect(() => { loadData(); }, [loadData]);

  return (
    <div className="space-y-6 p-4 md:p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <h1 className="text-2xl font-bold">{t("caisse.title")}</h1>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={loadData}>
            <RefreshCw className="size-4" />
          </Button>
          <NewMovementDialog onCreated={loadData} />
        </div>
      </div>

      {/* Balance Card */}
      <Card className="bg-gradient-to-r from-primary/10 to-primary/5">
        <CardContent className="p-6">
          <div className="flex items-center gap-3">
            <Wallet className="size-8 text-primary" />
            <div>
              <p className="text-sm text-muted-foreground">{t("caisse.balance")}</p>
              <p className={`text-3xl font-bold ${(data?.balance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
                {formatCurrency(data?.balance ?? 0)}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Monthly Summary */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_income")}</p>
            <p className="text-xl font-bold text-green-600">{formatCurrency(data?.monthIncome ?? 0)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_expense")}</p>
            <p className="text-xl font-bold text-red-600">{formatCurrency(data?.monthExpense ?? 0)}</p>
          </CardContent>
        </Card>
        <Card className="col-span-2 sm:col-span-1">
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_balance")}</p>
            <p className={`text-xl font-bold ${(data?.monthBalance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
              {formatCurrency(data?.monthBalance ?? 0)}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 items-center">
        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className="px-3 py-2 border border-input rounded-md bg-background text-sm"
        >
          <option value="">{t("common.all")}</option>
          <option value="income">{t("caisse.income")}</option>
          <option value="expense">{t("caisse.expense")}</option>
        </select>
        <Input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="w-40" />
        <Input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="w-40" />
        <Button variant="outline" size="sm" onClick={() => { setFilterType(""); setDateFrom(""); setDateTo(""); }}>
          {t("common.reset")}
        </Button>
      </div>

      {/* Movements Table */}
      {loading ? (
        <p className="text-center text-muted-foreground">{t("common.loading")}</p>
      ) : !data?.movements.length ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">
            {t("caisse.no_movements")}
          </CardContent>
        </Card>
      ) : (
        <div className="rounded-lg border overflow-x-auto">
          <table className="min-w-full divide-y divide-border">
            <thead className="bg-muted/50">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("common.date")}</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("common.type")}</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("payments.amount")}</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("common.category")}</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("common.payment_method")}</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase">{t("common.description")}</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground uppercase">{t("common.actions")}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {data.movements.map((m) => (
                <MovementRow key={m.id} movement={m} onUpdated={loadData} />
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function MovementRow({ movement, onUpdated }: { movement: CashMovement; onUpdated: () => void }) {
  const t = useT();
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  return (
    <>
      <tr className="hover:bg-muted/30">
        <td className="px-4 py-3 whitespace-nowrap text-sm">
          {new Date(movement.date).toLocaleDateString()}
        </td>
        <td className="px-4 py-3 whitespace-nowrap">
          <span className={`inline-flex items-center gap-1 text-sm font-medium ${movement.type === "income" ? "text-green-600" : "text-red-600"}`}>
            {movement.type === "income" ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}
            {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
          </span>
        </td>
        <td className="px-4 py-3 whitespace-nowrap text-sm font-medium">
          <span className={movement.type === "income" ? "text-green-600" : "text-red-600"}>
            {movement.type === "income" ? "+" : "-"}{formatCurrency(movement.amount)}
          </span>
        </td>
        <td className="px-4 py-3 whitespace-nowrap text-sm">{movement.category}</td>
        <td className="px-4 py-3 whitespace-nowrap text-sm text-muted-foreground">{movement.paymentMethod}</td>
        <td className="px-4 py-3 text-sm text-muted-foreground max-w-[200px] truncate">{movement.description || "—"}</td>
        <td className="px-4 py-3 whitespace-nowrap text-right">
          <div className="flex items-center justify-end gap-1">
            <div className="relative group">
              <Button
                variant="ghost"
                size="icon"
                className="size-8"
                disabled={movement.autoGenerated}
                onClick={() => setShowEdit(true)}
              >
                <Pencil className="size-4" />
              </Button>
              {movement.autoGenerated && (
                <div className="absolute bottom-full right-0 mb-1 hidden group-hover:block z-50">
                  <div className="bg-popover text-popover-foreground text-xs rounded-md px-3 py-1.5 shadow-md border whitespace-nowrap">
                    {t("caisse.auto_generated_hint")}
                  </div>
                </div>
              )}
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="size-8 text-destructive hover:text-destructive"
              onClick={() => setShowDelete(true)}
            >
              <Trash2 className="size-4" />
            </Button>
          </div>
        </td>
      </tr>

      {showEdit && (
        <EditMovementDialog
          movement={movement}
          onClose={() => setShowEdit(false)}
          onSaved={() => { setShowEdit(false); onUpdated(); }}
        />
      )}

      {showDelete && (
        <DeleteMovementDialog
          movement={movement}
          onClose={() => setShowDelete(false)}
          onDeleted={() => { setShowDelete(false); onUpdated(); }}
        />
      )}
    </>
  );
}

function EditMovementDialog({ movement, onClose, onSaved }: {
  movement: CashMovement;
  onClose: () => void;
  onSaved: () => void;
}) {
  const t = useT();
  const [amount, setAmount] = useState(String(movement.amount));
  const [category, setCategory] = useState(movement.category);
  const [description, setDescription] = useState(movement.description || "");
  const [date, setDate] = useState(movement.date);
  const [paymentMethod, setPaymentMethod] = useState(movement.paymentMethod);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch("/api/caisse/categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: Number(amount),
          category,
          description: description || null,
          date,
          paymentMethod,
        }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_updated"));
        onSaved();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.edit_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">General</option>
              {categories.filter((c) => c.type === movement.type).map((c) => (
                <option key={c.name} value={c.name}>{c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.date")}</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function DeleteMovementDialog({ movement, onClose, onDeleted }: {
  movement: CashMovement;
  onClose: () => void;
  onDeleted: () => void;
}) {
  const t = useT();
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, { method: "DELETE" });
      if (res.ok) {
        toast.success(t("caisse.movement_deleted"));
        onDeleted();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>{t("caisse.delete_movement")}</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">{t("caisse.delete_confirm")}</p>
        <div className="rounded-md border p-3 space-y-1 text-sm">
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.date")}:</span>
            <span>{new Date(movement.date).toLocaleDateString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.type")}:</span>
            <span className={movement.type === "income" ? "text-green-600" : "text-red-600"}>
              {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("payments.amount")}:</span>
            <span className="font-medium">{formatCurrency(movement.amount)}</span>
          </div>
          {movement.autoGenerated && movement.referenceId && (
            <p className="text-xs text-amber-600 mt-2">{t("caisse.auto_generated_hint")} {t("caisse.delete_confirm")}</p>
          )}
        </div>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? t("common.deleting") : t("common.delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function NewMovementDialog({ onCreated }: { onCreated: () => void }) {
  const t = useT();
  const [open, setOpen] = useState(false);
  const [type, setType] = useState<"income" | "expense">("income");
  const [category, setCategory] = useState("general");
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);

  useEffect(() => {
    if (open) {
      fetch("/api/caisse/categories")
        .then((r) => r.json())
        .then(setCategories)
        .catch(() => {});
    }
  }, [open]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch("/api/caisse", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type, category, amount: Number(amount), description: description || undefined, paymentMethod }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_created"));
        setOpen(false);
        onCreated();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="sm"><Plus className="size-4" /> {t("caisse.new_movement")}</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.new_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-2">
            <Button type="button" variant={type === "income" ? "default" : "outline"} onClick={() => setType("income")} className="flex-1">
              {t("caisse.income")}
            </Button>
            <Button type="button" variant={type === "expense" ? "default" : "outline"} onClick={() => setType("expense")} className="flex-1">
              {t("caisse.expense")}
            </Button>
          </div>
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">General</option>
              {categories.filter((c) => c.type === type).map((c) => (
                <option key={c.name} value={c.name}>{c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
