"use client";

import { useState, useEffect, useCallback } from "react";
import { useT, useI18n } from "@/lib/i18n";
import { formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter,
} from "@/components/ui/dialog";
import { Card, CardContent } from "@/components/ui/card";
import { Plus, ArrowUpRight, ArrowDownRight, Wallet, RefreshCw, Pencil, Trash2, Lock, Eye, EyeOff, Search, ChevronLeft, ChevronRight } from "lucide-react";
import { toast } from "sonner";

interface CashMovement {
  id: string;
  type: "income" | "expense";
  category: string;
  amount: number;
  description: string | null;
  paymentMethod: string;
  date: string;
  autoGenerated: boolean;
  referenceId?: string | null;
  createdAt: string;
}

interface CaisseData {
  movements: CashMovement[];
  balance: number;
  totalIncome: number;
  totalExpense: number;
  monthIncome: number;
  monthExpense: number;
  monthBalance: number;
}

export default function CaissePage() {
  const t = useT();
  const { direction } = useI18n();
  const align = direction === "rtl" ? "right" : "left";
  const [data, setData] = useState<CaisseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState<string>("");
  const [viewMonth, setViewMonth] = useState<string>(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  });
  const [search, setSearch] = useState("");
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [showBatchEdit, setShowBatchEdit] = useState(false);
  const [showBatchDelete, setShowBatchDelete] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [showPinDialog, setShowPinDialog] = useState(false);
  const [pinValue, setPinValue] = useState("");
  const [pinError, setPinError] = useState(false);

  const ADMIN_PIN = "profmanager1234";

  const handleReveal = (e: React.FormEvent) => {
    e.preventDefault();
    if (pinValue === ADMIN_PIN) {
      setRevealed(true);
      setPinValue("");
      setPinError(false);
      setShowPinDialog(false);
    } else {
      setPinError(true);
    }
  };

    function changeMonth(delta: number) {
    setViewMonth((prev) => {
      const [y, m] = prev.split("-").map(Number);
      const d = new Date(y, m - 1 + delta, 1);
      return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    });
  }

  const loadData = useCallback(async () => {
    setLoading(true);
    const [y, m] = viewMonth.split("-").map(Number);
    const firstOfMonth = `${y}-${String(m).padStart(2, "0")}-01`;
    const lastOfMonth = `${y}-${String(m).padStart(2, "0")}-${new Date(y, m, 0).getDate()}`;
    const params = new URLSearchParams();
    if (filterType) params.set("type", filterType);
    params.set("from", firstOfMonth);
    params.set("to", lastOfMonth);
    const res = await fetch(`/api/caisse?${params.toString()}`);
    if (res.ok) setData(await res.json());
    setLoading(false);
  }, [filterType, viewMonth]);

  useEffect(() => { loadData(); }, [loadData]);

  const filteredMovements = (data?.movements ?? []).filter((m) => {
    if (!search.trim()) return true;
    const q = search.trim().toLowerCase();
    const category = translateDescription(t, m.category) + " " + m.category;
    const method = METHOD_KEYS[m.paymentMethod] ? t(METHOD_KEYS[m.paymentMethod]) : m.paymentMethod;
    return [m.description, category, method, m.id]
      .filter(Boolean)
      .some((v) => v!.toLowerCase().includes(q));
  });

  return (
    <div className="space-y-6 p-4 md:p-6" dir={direction}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <h1 className="text-2xl font-bold">{t("caisse.title")}</h1>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => { setRevealed(false); loadData(); }}>
            <RefreshCw className="size-4" />
          </Button>
          <NewMovementDialog onCreated={loadData} />
        </div>
      </div>

      {/* Balance Card */}
      <Card className="bg-gradient-to-r from-primary/10 to-primary/5">
        <CardContent className="p-6">
          <div className="flex items-center gap-3">
            <Wallet className="size-8 text-primary" />
            <div className="flex-1">
              <p className="text-sm text-muted-foreground">{t("caisse.balance")}</p>
              <p className={`text-3xl font-bold ${(data?.balance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
                {revealed ? formatCurrency(data?.balance ?? 0) : "••••••"}
              </p>
            </div>
            {!revealed ? (
              <Button variant="outline" size="sm" onClick={() => setShowPinDialog(true)}>
                <Lock className="size-4" /> {t("caisse.reveal")}
              </Button>
            ) : (
              <Button variant="outline" size="sm" onClick={() => setRevealed(false)}>
                <EyeOff className="size-4" /> {t("caisse.hide")}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Monthly Summary */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_income")}</p>
            <p className="text-xl font-bold text-green-600">{revealed ? formatCurrency(data?.monthIncome ?? 0) : "••••••"}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_expense")}</p>
            <p className="text-xl font-bold text-red-600">{revealed ? formatCurrency(data?.monthExpense ?? 0) : "••••••"}</p>
          </CardContent>
        </Card>
        <Card className="col-span-2 sm:col-span-1">
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">{t("caisse.month_balance")}</p>
            <p className={`text-xl font-bold ${(data?.monthBalance ?? 0) >= 0 ? "text-green-600" : "text-red-600"}`}>
              {revealed ? formatCurrency(data?.monthBalance ?? 0) : "••••••"}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* PIN Dialog */}
      {showPinDialog && (
        <Dialog open onOpenChange={setShowPinDialog}>
          <DialogContent className="max-w-sm">
            <DialogHeader>
              <DialogTitle>{t("caisse.pin_required")}</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleReveal} className="space-y-4">
              <Input
                type="password"
                value={pinValue}
                onChange={(e) => { setPinValue(e.target.value); setPinError(false); }}
                autoFocus
                autoComplete="off"
              />
              {pinError && <p className="text-sm text-destructive">{t("caisse.wrong_password")}</p>}
              <DialogFooter>
                <Button type="button" variant="outline" onClick={() => { setShowPinDialog(false); setPinValue(""); setPinError(false); }}>
                  {t("common.cancel")}
                </Button>
                <Button type="submit"><Eye className="size-4" /> {t("caisse.reveal")}</Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-2 items-center">
        <div className="relative">
          <Search className="absolute start-2.5 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder={t("common.search")}
            className="w-56 ps-8"
          />
        </div>
        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className="px-3 py-2 border border-input rounded-md bg-background text-sm"
        >
          <option value="">{t("common.all")}</option>
          <option value="income">{t("caisse.income")}</option>
          <option value="expense">{t("caisse.expense")}</option>
        </select>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" onClick={() => changeMonth(-1)} title={t("payments.prev_month")}>
            {direction === "rtl" ? <ChevronRight className="size-4" /> : <ChevronLeft className="size-4" />}
          </Button>
          <Input type="month" value={viewMonth} onChange={(e) => e.target.value && setViewMonth(e.target.value)} className="w-44" aria-label={t("payments.month")} />
          <Button variant="outline" size="icon" onClick={() => changeMonth(1)} title={t("payments.next_month")}>
            {direction === "rtl" ? <ChevronLeft className="size-4" /> : <ChevronRight className="size-4" />}
          </Button>
        </div>
      </div>

      {/* Selection toolbar */}
      {selectedIds.size > 0 && (
        <div className="flex flex-wrap items-center gap-2 rounded-lg border bg-muted/30 px-4 py-2">
          <span className="text-sm font-medium">{selectedIds.size} {t("caisse.selected")}</span>
          <div className="flex-1" />
          <Button variant="outline" size="sm" onClick={() => setShowBatchEdit(true)}>
            <Pencil className="size-4" /> {t("caisse.batch_edit")}
          </Button>
          <Button variant="destructive" size="sm" onClick={() => setShowBatchDelete(true)}>
            <Trash2 className="size-4" /> {t("caisse.batch_delete")}
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setSelectedIds(new Set())}>
            {t("common.cancel")}
          </Button>
        </div>
      )}

      {/* Movements Table */}
      {loading ? (
        <p className="text-center text-muted-foreground">{t("common.loading")}</p>
      ) : !filteredMovements.length ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">
            {t("caisse.no_movements")}
          </CardContent>
        </Card>
      ) : (
        <div className="overflow-x-auto rounded-lg border">
          <table className="w-full border-collapse" style={{ tableLayout: "fixed", minWidth: "960px" }}>
            <colgroup>
              <col style={{ width: "4%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "9%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "13%" }} />
              <col style={{ width: "27%" }} />
              <col style={{ width: "11%" }} />
            </colgroup>
            <thead>
              <tr className="bg-muted/50 border-b">
                <th style={{ textAlign: "center", padding: "12px" }}>
                  <input
                    type="checkbox"
                    className="size-4 accent-primary"
                    checked={filteredMovements.length > 0 && filteredMovements.every((m) => selectedIds.has(m.id))}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setSelectedIds(new Set(filteredMovements.map((m) => m.id)));
                      } else {
                        setSelectedIds(new Set());
                      }
                    }}
                  />
                </th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.date")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.type")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("payments.amount")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.category")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.payment_method")}</th>
                <th style={{ textAlign: align, padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.description")}</th>
                <th style={{ textAlign: "center", padding: "12px", fontWeight: 600, fontSize: "13px", color: "hsl(var(--foreground))" }}>{t("common.actions")}</th>
              </tr>
            </thead>
            <tbody>
              {filteredMovements.map((m, i) => (
                <MovementRow
                  key={m.id}
                  movement={m}
                  onUpdated={loadData}
                  zebra={i % 2 === 1}
                  selected={selectedIds.has(m.id)}
                  onSelect={(checked) => {
                    const next = new Set(selectedIds);
                    if (checked) next.add(m.id);
                    else next.delete(m.id);
                    setSelectedIds(next);
                  }}
                />
              ))}
            </tbody>
          </table>
        </div>
      )}

      {showBatchEdit && (
        <BatchEditDialog
          ids={[...selectedIds]}
          onClose={() => setShowBatchEdit(false)}
          onSaved={() => { setShowBatchEdit(false); setSelectedIds(new Set()); loadData(); }}
        />
      )}
      {showBatchDelete && (
        <BatchDeleteDialog
          ids={[...selectedIds]}
          onClose={() => setShowBatchDelete(false)}
          onDeleted={() => { setShowBatchDelete(false); setSelectedIds(new Set()); loadData(); }}
        />
      )}
    </div>
  );
}

const CATEGORY_KEYS: Record<string, string> = {
  Paiement: "caisse.category_payment",
  Salaire: "caisse.category_salary",
  Fournitures: "caisse.category_supplies",
  general: "caisse.category_general",
};

const METHOD_KEYS: Record<string, string> = {
  cash: "payments.cash",
  cheque: "payments.cheque",
  transfer: "payments.transfer",
  card: "payments.card",
};

function translateDescription(t: (k: string) => string, desc: string | null): string {
  if (!desc) return "—";
  return desc
    .replace(/^Paiement suppl\u00e9mentaire/, t("caisse.description_additional"))
    .replace(/^Paiement/, t("caisse.description_payment"))
    .replace(/^Annulation paiement/, t("caisse.description_cancellation"))
    .replace(/^Salaire enseignant/, t("caisse.description_salary"));
}

function MovementRow({ movement, onUpdated, zebra, selected, onSelect }: {
  movement: CashMovement;
  onUpdated: () => void;
  zebra: boolean;
  selected: boolean;
  onSelect: (checked: boolean) => void;
}) {
  const t = useT();
  const { direction } = useI18n();
  const align = direction === "rtl" ? "right" : "left";
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  const categoryLabel = CATEGORY_KEYS[movement.category]
    ? t(CATEGORY_KEYS[movement.category])
    : movement.category;
  const methodLabel = METHOD_KEYS[movement.paymentMethod]
    ? t(METHOD_KEYS[movement.paymentMethod])
    : movement.paymentMethod;
  const descriptionLabel = translateDescription(t, movement.description);

  return (
    <>
      <tr className={`border-b ${zebra ? "bg-muted/20" : "bg-background"}`}>
        <td style={{ padding: "12px", textAlign: "center" }}>
          <input
            type="checkbox"
            className="size-4 accent-primary"
            checked={selected}
            onChange={(e) => onSelect(e.target.checked)}
          />
        </td>
        <td style={{ padding: "12px", textAlign: align, fontWeight: 600, fontSize: "14px", color: "hsl(var(--foreground))" }}>
          {new Date(movement.date).toLocaleDateString()}
        </td>
        <td style={{ padding: "12px", textAlign: align }}>
          <span className={`inline-flex items-center gap-1 text-sm font-medium ${movement.type === "income" ? "text-green-600" : "text-red-600"}`}>
            {movement.type === "income" ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}
            {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
          </span>
        </td>
        <td style={{ padding: "12px", textAlign: align }}>
          <span className={`text-sm font-medium ${movement.type === "income" ? "text-green-600" : "text-red-600"}`}>
            {movement.type === "income" ? "+" : "-"}{formatCurrency(movement.amount)}
          </span>
        </td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--foreground))" }}>{categoryLabel}</td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--muted-foreground))" }}>{methodLabel}</td>
        <td style={{ padding: "12px", textAlign: align, fontSize: "14px", color: "hsl(var(--muted-foreground))", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{descriptionLabel}</td>
        <td style={{ padding: "12px", textAlign: "center" }}>
          <div className="flex items-center justify-center gap-1">
            <div className="relative group">
              <Button
                variant="ghost"
                size="icon"
                className="size-8"
                disabled={movement.autoGenerated}
                onClick={() => setShowEdit(true)}
              >
                <Pencil className="size-4" />
              </Button>
              {movement.autoGenerated && (
                <div className="absolute bottom-full right-0 mb-1 hidden group-hover:block z-50">
                  <div className="bg-popover text-popover-foreground text-xs rounded-md px-3 py-1.5 shadow-md border whitespace-nowrap">
                    {t("caisse.auto_generated_hint")}
                  </div>
                </div>
              )}
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="size-8 text-destructive hover:text-destructive"
              onClick={() => setShowDelete(true)}
            >
              <Trash2 className="size-4" />
            </Button>
          </div>
        </td>
      </tr>

      {showEdit && (
        <EditMovementDialog
          movement={movement}
          onClose={() => setShowEdit(false)}
          onSaved={() => { setShowEdit(false); onUpdated(); }}
        />
      )}

      {showDelete && (
        <DeleteMovementDialog
          movement={movement}
          onClose={() => setShowDelete(false)}
          onDeleted={() => { setShowDelete(false); onUpdated(); }}
        />
      )}
    </>
  );
}

function EditMovementDialog({ movement, onClose, onSaved }: {
  movement: CashMovement;
  onClose: () => void;
  onSaved: () => void;
}) {
  const t = useT();
  const [amount, setAmount] = useState(String(movement.amount));
  const [category, setCategory] = useState(movement.category);
  const [description, setDescription] = useState(movement.description || "");
  const [date, setDate] = useState(movement.date);
  const [paymentMethod, setPaymentMethod] = useState(movement.paymentMethod);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch("/api/caisse/categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: Number(amount),
          category,
          description: description || null,
          date,
          paymentMethod,
        }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_updated"));
        onSaved();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.edit_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">General</option>
              {categories.filter((c) => c.type === movement.type).map((c) => (
                <option key={c.name} value={c.name}>{c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.date")}</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function DeleteMovementDialog({ movement, onClose, onDeleted }: {
  movement: CashMovement;
  onClose: () => void;
  onDeleted: () => void;
}) {
  const t = useT();
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    try {
      const res = await fetch(`/api/caisse/${movement.id}`, { method: "DELETE" });
      if (res.ok) {
        toast.success(t("caisse.movement_deleted"));
        onDeleted();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>{t("caisse.delete_movement")}</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">{t("caisse.delete_confirm")}</p>
        <div className="rounded-md border p-3 space-y-1 text-sm">
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.date")}:</span>
            <span>{new Date(movement.date).toLocaleDateString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("common.type")}:</span>
            <span className={movement.type === "income" ? "text-green-600" : "text-red-600"}>
              {movement.type === "income" ? t("caisse.income") : t("caisse.expense")}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">{t("payments.amount")}:</span>
            <span className="font-medium">{formatCurrency(movement.amount)}</span>
          </div>
          {movement.autoGenerated && movement.referenceId && (
            <p className="text-xs text-amber-600 mt-2">{t("caisse.auto_generated_hint")} {t("caisse.delete_confirm")}</p>
          )}
        </div>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? t("common.deleting") : t("common.delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function NewMovementDialog({ onCreated }: { onCreated: () => void }) {
  const t = useT();
  const [open, setOpen] = useState(false);
  const [type, setType] = useState<"income" | "expense">("income");
  const [category, setCategory] = useState("general");
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);

  useEffect(() => {
    if (open) {
      fetch("/api/caisse/categories")
        .then((r) => r.json())
        .then(setCategories)
        .catch(() => {});
    }
  }, [open]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!amount || Number(amount) <= 0) return;
    setSaving(true);
    try {
      const res = await fetch("/api/caisse", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type, category, amount: Number(amount), description: description || undefined, paymentMethod }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_created"));
        setOpen(false);
        onCreated();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="sm"><Plus className="size-4" /> {t("caisse.new_movement")}</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.new_movement")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-2">
            <Button type="button" variant={type === "income" ? "default" : "outline"} onClick={() => setType("income")} className="flex-1">
              {t("caisse.income")}
            </Button>
            <Button type="button" variant={type === "expense" ? "default" : "outline"} onClick={() => setType("expense")} className="flex-1">
              {t("caisse.expense")}
            </Button>
          </div>
          <div className="space-y-2">
            <Label>{t("payments.amount")}</Label>
            <Input type="number" min="0" step="100" value={amount} onChange={(e) => setAmount(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="general">General</option>
              {categories.filter((c) => c.type === type).map((c) => (
                <option key={c.name} value={c.name}>{c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function BatchEditDialog({ ids, onClose, onSaved }: {
  ids: string[];
  onClose: () => void;
  onSaved: () => void;
}) {
  const t = useT();
  const [date, setDate] = useState("");
  const [category, setCategory] = useState("");
  const [description, setDescription] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("");
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<{ name: string; type: string }[]>([]);

  useEffect(() => {
    fetch("/api/caisse/categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const updates: Record<string, unknown> = {};
    if (date) updates.date = date;
    if (category) updates.category = category;
    if (description.trim()) updates.description = description.trim();
    if (paymentMethod) updates.paymentMethod = paymentMethod;
    if (Object.keys(updates).length === 0) return;
    setSaving(true);
    try {
      const res = await fetch("/api/caisse/batch", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids, updates }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_updated"));
        onSaved();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("caisse.batch_edit")}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <p className="text-sm text-muted-foreground">{t("caisse.batch_edit_hint")}</p>
          <div className="space-y-2">
            <Label>{t("common.date")}</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>{t("common.category")}</Label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="">{t("caisse.batch_keep")}</option>
              <option value="general">General</option>
              {categories.map((c) => (
                <option key={c.name} value={c.name}>{c.name}</option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.payment_method")}</Label>
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm"
            >
              <option value="">{t("caisse.batch_keep")}</option>
              <option value="cash">{t("payments.cash")}</option>
              <option value="cheque">{t("payments.cheque")}</option>
              <option value="transfer">{t("payments.transfer")}</option>
              <option value="card">{t("payments.card")}</option>
            </select>
          </div>
          <div className="space-y-2">
            <Label>{t("common.description")}</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
            <Button type="submit" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function BatchDeleteDialog({ ids, onClose, onDeleted }: {
  ids: string[];
  onClose: () => void;
  onDeleted: () => void;
}) {
  const t = useT();
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    try {
      const res = await fetch("/api/caisse/batch", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids }),
      });
      if (res.ok) {
        toast.success(t("caisse.movement_deleted"));
        onDeleted();
      } else {
        const err = await res.json();
        toast.error(err.error || t("common.error"));
      }
    } catch {
      toast.error(t("common.error"));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>{t("caisse.batch_delete")}</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">{t("caisse.batch_delete_confirm", { count: ids.length })}</p>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={onClose}>{t("common.cancel")}</Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? t("common.deleting") : t("common.delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
