import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";

export async function PATCH(req: NextRequest) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const body = await req.json();
    const { ids, updates } = body as { ids: string[]; updates: Record<string, unknown> };

    if (!Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: "No movements selected" }, { status: 400 });
    }

    const updateFields: Record<string, unknown> = {};
    if (updates.amount !== undefined) updateFields.amount = Number(updates.amount);
    if (updates.category !== undefined) updateFields.category = updates.category;
    if (updates.description !== undefined) updateFields.description = updates.description;
    if (updates.date !== undefined) updateFields.date = updates.date;
    if (updates.paymentMethod !== undefined) updateFields.paymentMethod = updates.paymentMethod;

    if (Object.keys(updateFields).length === 0) {
      return NextResponse.json({ error: "No fields to update" }, { status: 400 });
    }

    const { data: existing } = await supabase
      .from("cash_movements")
      .select("id, autoGenerated")
      .in("id", ids)
      .eq("tenantId", tenantId);

    const editable = (existing || []).filter((m: any) => !m.autoGenerated).map((m: any) => m.id);
    if (editable.length === 0) {
      return NextResponse.json({ error: "Selected movements cannot be edited (auto-generated)" }, { status: 400 });
    }

    const { error } = await supabase
      .from("cash_movements")
      .update(updateFields)
      .in("id", editable)
      .eq("tenantId", tenantId);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, updated: editable.length });
  } catch {
    return NextResponse.json({ error: "Failed to update cash movements" }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const body = await req.json();
    const { ids } = body as { ids: string[] };

    if (!Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: "No movements selected" }, { status: 400 });
    }

    const { data: existing } = await supabase
      .from("cash_movements")
      .select("*")
      .in("id", ids)
      .eq("tenantId", tenantId);

    if (!existing || existing.length === 0) {
      return NextResponse.json({ error: "Movements not found" }, { status: 404 });
    }

    for (const m of existing) {
      if (m.autoGenerated && m.referenceId) {
        const { data: payment } = await supabase
          .from("payments")
          .select("id, amountDue, amountPaid, studentId")
          .eq("id", m.referenceId)
          .eq("tenantId", tenantId)
          .single();

        if (payment) {
          if (Number(payment.amountPaid) > Number(payment.amountDue)) {
            const excess = Number(payment.amountPaid) - Number(payment.amountDue);
            const { data: studentData } = await supabase
              .from("students")
              .select("advanceBalance")
              .eq("id", payment.studentId)
              .single();
            const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
            await supabase
              .from("students")
              .update({ advanceBalance: Math.max(0, currentAdvance - excess) })
              .eq("id", payment.studentId);
          }

          await supabase.from("cash_movements").delete().eq("referenceId", payment.id).eq("autoGenerated", true);
          await supabase.from("payments").delete().eq("id", payment.id);
        } else {
          await supabase.from("cash_movements").delete().eq("id", m.id);
        }
      } else {
        await supabase.from("cash_movements").delete().eq("id", m.id);
      }
    }

    return NextResponse.json({ success: true, deleted: existing.length });
  } catch {
    return NextResponse.json({ error: "Failed to delete cash movements" }, { status: 500 });
  }
}
