import { NextRequest, NextResponse } from "next/server";
import { getTenantContext } from "@/lib/auth";
import { calculateStatus, normalizePayment } from "@/lib/payments/utils";

export async function GET(req: NextRequest) {
  try {
    const { tenantId, supabase } = await getTenantContext();
    const { searchParams } = new URL(req.url);
    const year = parseInt(searchParams.get("year") || String(new Date().getFullYear()));
    const month = parseInt(searchParams.get("month") || String(new Date().getMonth() + 1));
    const studentId = searchParams.get("studentId");
    const statusFilter = searchParams.get("status");

    const firstOfMonth = `${year}-${String(month).padStart(2, "0")}-01`;

    let query = supabase
      .from("payments")
      .select("*, students(id, fullName, monthlyFee, group_students(*, groups(name)))")
      .eq("tenantId", tenantId)
      .eq("month", firstOfMonth);

    if (studentId) query = query.eq("studentId", studentId);

    const { data: payments } = await query.order("createdAt", { ascending: false });

    const normalized = (payments || []).map(normalizePayment).map((p: any) => {
      const computedStatus = calculateStatus(Number(p.amountDue), Number(p.amountPaid), new Date(p.month));
      return { ...p, status: computedStatus };
    });

    if (statusFilter) {
      return NextResponse.json(normalized.filter((p: any) => p.status === statusFilter));
    }

    return NextResponse.json(normalized);
  } catch {
    return NextResponse.json({ error: "Failed to fetch payments" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { tenantId, supabase, userId } = await getTenantContext();
    const body = await req.json();
    const { studentId, month, amount, note } = body;

    if (!studentId || !month || !amount) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const paymentDate = `${month.slice(0, 7)}-01`;

    const { data: existing } = await supabase
      .from("payments")
      .select("*")
      .eq("tenantId", tenantId)
      .eq("studentId", studentId)
      .eq("month", paymentDate)
      .maybeSingle();

    if (existing) {
      const newPaid = Number(existing.amountPaid) + Number(amount);
      const amountDue = Number(existing.amountDue);
      const newStatus = calculateStatus(amountDue, newPaid, new Date(paymentDate));
      const paidAt = newStatus === "paid" ? new Date().toISOString() : existing.paidAt;

      const updateFields: Record<string, unknown> = {
        amountPaid: newPaid,
        status: newStatus,
        paidAt: paidAt,
        updatedAt: new Date().toISOString(),
      };
      if (note !== undefined) updateFields.note = note;

      // receiptNumber / receiptSequence columns removed from schema — skip

      const { data: updated, error: updateError } = await supabase
        .from("payments")
        .update(updateFields)
        .eq("id", existing.id)
        .select("*, students(id, fullName, monthlyFee, group_students(*, groups(name)))")
        .single();

      if (updateError || !updated) {
        return NextResponse.json(
          { error: updateError?.message || "Failed to update payment" },
          { status: 500 }
        );
      }

      if (Number(amount) > 0) {
        await supabase
          .from("cash_movements")
          .insert({
            id: crypto.randomUUID(),
            tenantId,
            userId,
            type: "income",
            category: "Paiement",
            amount: Number(amount),
            description: `Paiement supplémentaire — ${existing.students?.fullName || "Élève"} — ${paymentDate}`,
            paymentMethod: "cash",
            date: new Date().toISOString().split("T")[0],
            referenceId: existing.id,
            autoGenerated: true,
          })
          .maybeSingle();
      }

      if (newPaid > amountDue) {
        const excess = newPaid - amountDue;
        const { data: studentData } = await supabase
          .from("students")
          .select("advanceBalance")
          .eq("id", studentId)
          .single();
        const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
        await supabase
          .from("students")
          .update({ advanceBalance: currentAdvance + excess })
          .eq("id", studentId);
      }

      return NextResponse.json(normalizePayment(updated));
    }

    const { data: student } = await supabase
      .from("students")
      .select("monthlyFee")
      .eq("id", studentId)
      .eq("tenantId", tenantId)
      .single();

    const amountDue = Number(student?.monthlyFee) || Number(amount);
    const status = calculateStatus(amountDue, Number(amount), new Date(paymentDate));
    const paidAt = status === "paid" ? new Date().toISOString() : null;

    const insertFields: Record<string, unknown> = {
      id: crypto.randomUUID(),
      tenantId: tenantId,
      studentId: studentId,
      month: paymentDate,
      amountDue: amountDue,
      amountPaid: Number(amount),
      status,
      paidAt: paidAt,
      updatedAt: new Date().toISOString(),
    };
    if (note) insertFields.note = note;

    // receiptNumber / receiptSequence columns removed from schema — skip

    const { data: payment, error: insertError } = await supabase
      .from("payments")
      .insert(insertFields)
      .select("*, students(id, fullName, monthlyFee, group_students(*, groups(name)))")
      .single();

    if (insertError || !payment) {
      return NextResponse.json(
        { error: insertError?.message || "Failed to create payment" },
        { status: 500 }
      );
    }

    if (Number(amount) > 0) {
      await supabase
        .from("cash_movements")
        .insert({
          id: crypto.randomUUID(),
          tenantId,
          userId,
          type: "income",
          category: "Paiement",
          amount: Number(amount),
          description: `Paiement — ${payment.students?.fullName || "Élève"} — ${paymentDate}`,
          paymentMethod: "cash",
          date: new Date().toISOString().split("T")[0],
          referenceId: payment.id,
          autoGenerated: true,
        })
        .maybeSingle();
    }

    if (Number(amount) > amountDue) {
      const excess = Number(amount) - amountDue;
      const { data: studentData } = await supabase
        .from("students")
        .select("advanceBalance")
        .eq("id", studentId)
        .single();
      const currentAdvance = Number((studentData as any)?.advanceBalance || 0);
      await supabase
        .from("students")
        .update({ advanceBalance: currentAdvance + excess })
        .eq("id", studentId);
    }

    return NextResponse.json(normalizePayment(payment), { status: 201 });
  } catch {
    return NextResponse.json({ error: "Failed to create payment" }, { status: 500 });
  }
}
